// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                       = new(Query)
	Customer                *customer
	Kabupaten               *kabupaten
	Kecamatan               *kecamatan
	Kelurahan               *kelurahan
	LeasingContract         *leasingContract
	LeasingContractDocument *leasingContractDocument
	LeasingProduct          *leasingProduct
	LeasingTask             *leasingTask
	LeasingTasksAttribute   *leasingTasksAttribute
	Location                *location
	Motor                   *motor
	MotorAsset              *motorAsset
	MotorType               *motorType
	OauthProvider           *oauthProvider
	Permission              *permission
	Province                *province
	Role                    *role
	RolePermission          *rolePermission
	TemplateTask            *templateTask
	TemplateTaskAttribute   *templateTaskAttribute
	User                    *user
	UserOauthProvider       *userOauthProvider
	UserRole                *userRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Customer = &Q.Customer
	Kabupaten = &Q.Kabupaten
	Kecamatan = &Q.Kecamatan
	Kelurahan = &Q.Kelurahan
	LeasingContract = &Q.LeasingContract
	LeasingContractDocument = &Q.LeasingContractDocument
	LeasingProduct = &Q.LeasingProduct
	LeasingTask = &Q.LeasingTask
	LeasingTasksAttribute = &Q.LeasingTasksAttribute
	Location = &Q.Location
	Motor = &Q.Motor
	MotorAsset = &Q.MotorAsset
	MotorType = &Q.MotorType
	OauthProvider = &Q.OauthProvider
	Permission = &Q.Permission
	Province = &Q.Province
	Role = &Q.Role
	RolePermission = &Q.RolePermission
	TemplateTask = &Q.TemplateTask
	TemplateTaskAttribute = &Q.TemplateTaskAttribute
	User = &Q.User
	UserOauthProvider = &Q.UserOauthProvider
	UserRole = &Q.UserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                      db,
		Customer:                newCustomer(db, opts...),
		Kabupaten:               newKabupaten(db, opts...),
		Kecamatan:               newKecamatan(db, opts...),
		Kelurahan:               newKelurahan(db, opts...),
		LeasingContract:         newLeasingContract(db, opts...),
		LeasingContractDocument: newLeasingContractDocument(db, opts...),
		LeasingProduct:          newLeasingProduct(db, opts...),
		LeasingTask:             newLeasingTask(db, opts...),
		LeasingTasksAttribute:   newLeasingTasksAttribute(db, opts...),
		Location:                newLocation(db, opts...),
		Motor:                   newMotor(db, opts...),
		MotorAsset:              newMotorAsset(db, opts...),
		MotorType:               newMotorType(db, opts...),
		OauthProvider:           newOauthProvider(db, opts...),
		Permission:              newPermission(db, opts...),
		Province:                newProvince(db, opts...),
		Role:                    newRole(db, opts...),
		RolePermission:          newRolePermission(db, opts...),
		TemplateTask:            newTemplateTask(db, opts...),
		TemplateTaskAttribute:   newTemplateTaskAttribute(db, opts...),
		User:                    newUser(db, opts...),
		UserOauthProvider:       newUserOauthProvider(db, opts...),
		UserRole:                newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Customer                customer
	Kabupaten               kabupaten
	Kecamatan               kecamatan
	Kelurahan               kelurahan
	LeasingContract         leasingContract
	LeasingContractDocument leasingContractDocument
	LeasingProduct          leasingProduct
	LeasingTask             leasingTask
	LeasingTasksAttribute   leasingTasksAttribute
	Location                location
	Motor                   motor
	MotorAsset              motorAsset
	MotorType               motorType
	OauthProvider           oauthProvider
	Permission              permission
	Province                province
	Role                    role
	RolePermission          rolePermission
	TemplateTask            templateTask
	TemplateTaskAttribute   templateTaskAttribute
	User                    user
	UserOauthProvider       userOauthProvider
	UserRole                userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		Customer:                q.Customer.clone(db),
		Kabupaten:               q.Kabupaten.clone(db),
		Kecamatan:               q.Kecamatan.clone(db),
		Kelurahan:               q.Kelurahan.clone(db),
		LeasingContract:         q.LeasingContract.clone(db),
		LeasingContractDocument: q.LeasingContractDocument.clone(db),
		LeasingProduct:          q.LeasingProduct.clone(db),
		LeasingTask:             q.LeasingTask.clone(db),
		LeasingTasksAttribute:   q.LeasingTasksAttribute.clone(db),
		Location:                q.Location.clone(db),
		Motor:                   q.Motor.clone(db),
		MotorAsset:              q.MotorAsset.clone(db),
		MotorType:               q.MotorType.clone(db),
		OauthProvider:           q.OauthProvider.clone(db),
		Permission:              q.Permission.clone(db),
		Province:                q.Province.clone(db),
		Role:                    q.Role.clone(db),
		RolePermission:          q.RolePermission.clone(db),
		TemplateTask:            q.TemplateTask.clone(db),
		TemplateTaskAttribute:   q.TemplateTaskAttribute.clone(db),
		User:                    q.User.clone(db),
		UserOauthProvider:       q.UserOauthProvider.clone(db),
		UserRole:                q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		Customer:                q.Customer.replaceDB(db),
		Kabupaten:               q.Kabupaten.replaceDB(db),
		Kecamatan:               q.Kecamatan.replaceDB(db),
		Kelurahan:               q.Kelurahan.replaceDB(db),
		LeasingContract:         q.LeasingContract.replaceDB(db),
		LeasingContractDocument: q.LeasingContractDocument.replaceDB(db),
		LeasingProduct:          q.LeasingProduct.replaceDB(db),
		LeasingTask:             q.LeasingTask.replaceDB(db),
		LeasingTasksAttribute:   q.LeasingTasksAttribute.replaceDB(db),
		Location:                q.Location.replaceDB(db),
		Motor:                   q.Motor.replaceDB(db),
		MotorAsset:              q.MotorAsset.replaceDB(db),
		MotorType:               q.MotorType.replaceDB(db),
		OauthProvider:           q.OauthProvider.replaceDB(db),
		Permission:              q.Permission.replaceDB(db),
		Province:                q.Province.replaceDB(db),
		Role:                    q.Role.replaceDB(db),
		RolePermission:          q.RolePermission.replaceDB(db),
		TemplateTask:            q.TemplateTask.replaceDB(db),
		TemplateTaskAttribute:   q.TemplateTaskAttribute.replaceDB(db),
		User:                    q.User.replaceDB(db),
		UserOauthProvider:       q.UserOauthProvider.replaceDB(db),
		UserRole:                q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	Customer                ICustomerDo
	Kabupaten               IKabupatenDo
	Kecamatan               IKecamatanDo
	Kelurahan               IKelurahanDo
	LeasingContract         ILeasingContractDo
	LeasingContractDocument ILeasingContractDocumentDo
	LeasingProduct          ILeasingProductDo
	LeasingTask             ILeasingTaskDo
	LeasingTasksAttribute   ILeasingTasksAttributeDo
	Location                ILocationDo
	Motor                   IMotorDo
	MotorAsset              IMotorAssetDo
	MotorType               IMotorTypeDo
	OauthProvider           IOauthProviderDo
	Permission              IPermissionDo
	Province                IProvinceDo
	Role                    IRoleDo
	RolePermission          IRolePermissionDo
	TemplateTask            ITemplateTaskDo
	TemplateTaskAttribute   ITemplateTaskAttributeDo
	User                    IUserDo
	UserOauthProvider       IUserOauthProviderDo
	UserRole                IUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Customer:                q.Customer.WithContext(ctx),
		Kabupaten:               q.Kabupaten.WithContext(ctx),
		Kecamatan:               q.Kecamatan.WithContext(ctx),
		Kelurahan:               q.Kelurahan.WithContext(ctx),
		LeasingContract:         q.LeasingContract.WithContext(ctx),
		LeasingContractDocument: q.LeasingContractDocument.WithContext(ctx),
		LeasingProduct:          q.LeasingProduct.WithContext(ctx),
		LeasingTask:             q.LeasingTask.WithContext(ctx),
		LeasingTasksAttribute:   q.LeasingTasksAttribute.WithContext(ctx),
		Location:                q.Location.WithContext(ctx),
		Motor:                   q.Motor.WithContext(ctx),
		MotorAsset:              q.MotorAsset.WithContext(ctx),
		MotorType:               q.MotorType.WithContext(ctx),
		OauthProvider:           q.OauthProvider.WithContext(ctx),
		Permission:              q.Permission.WithContext(ctx),
		Province:                q.Province.WithContext(ctx),
		Role:                    q.Role.WithContext(ctx),
		RolePermission:          q.RolePermission.WithContext(ctx),
		TemplateTask:            q.TemplateTask.WithContext(ctx),
		TemplateTaskAttribute:   q.TemplateTaskAttribute.WithContext(ctx),
		User:                    q.User.WithContext(ctx),
		UserOauthProvider:       q.UserOauthProvider.WithContext(ctx),
		UserRole:                q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
