// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newKabupaten(db *gorm.DB, opts ...gen.DOOption) kabupaten {
	_kabupaten := kabupaten{}

	_kabupaten.kabupatenDo.UseDB(db, opts...)
	_kabupaten.kabupatenDo.UseModel(&model.Kabupaten{})

	tableName := _kabupaten.kabupatenDo.TableName()
	_kabupaten.ALL = field.NewAsterisk(tableName)
	_kabupaten.KabID = field.NewInt64(tableName, "kab_id")
	_kabupaten.KabName = field.NewString(tableName, "kab_name")
	_kabupaten.ProvID = field.NewInt64(tableName, "prov_id")

	_kabupaten.fillFieldMap()

	return _kabupaten
}

type kabupaten struct {
	kabupatenDo

	ALL     field.Asterisk
	KabID   field.Int64
	KabName field.String
	ProvID  field.Int64

	fieldMap map[string]field.Expr
}

func (k kabupaten) Table(newTableName string) *kabupaten {
	k.kabupatenDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kabupaten) As(alias string) *kabupaten {
	k.kabupatenDo.DO = *(k.kabupatenDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kabupaten) updateTableName(table string) *kabupaten {
	k.ALL = field.NewAsterisk(table)
	k.KabID = field.NewInt64(table, "kab_id")
	k.KabName = field.NewString(table, "kab_name")
	k.ProvID = field.NewInt64(table, "prov_id")

	k.fillFieldMap()

	return k
}

func (k *kabupaten) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kabupaten) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 3)
	k.fieldMap["kab_id"] = k.KabID
	k.fieldMap["kab_name"] = k.KabName
	k.fieldMap["prov_id"] = k.ProvID
}

func (k kabupaten) clone(db *gorm.DB) kabupaten {
	k.kabupatenDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kabupaten) replaceDB(db *gorm.DB) kabupaten {
	k.kabupatenDo.ReplaceDB(db)
	return k
}

type kabupatenDo struct{ gen.DO }

type IKabupatenDo interface {
	gen.SubQuery
	Debug() IKabupatenDo
	WithContext(ctx context.Context) IKabupatenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKabupatenDo
	WriteDB() IKabupatenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKabupatenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKabupatenDo
	Not(conds ...gen.Condition) IKabupatenDo
	Or(conds ...gen.Condition) IKabupatenDo
	Select(conds ...field.Expr) IKabupatenDo
	Where(conds ...gen.Condition) IKabupatenDo
	Order(conds ...field.Expr) IKabupatenDo
	Distinct(cols ...field.Expr) IKabupatenDo
	Omit(cols ...field.Expr) IKabupatenDo
	Join(table schema.Tabler, on ...field.Expr) IKabupatenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKabupatenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKabupatenDo
	Group(cols ...field.Expr) IKabupatenDo
	Having(conds ...gen.Condition) IKabupatenDo
	Limit(limit int) IKabupatenDo
	Offset(offset int) IKabupatenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKabupatenDo
	Unscoped() IKabupatenDo
	Create(values ...*model.Kabupaten) error
	CreateInBatches(values []*model.Kabupaten, batchSize int) error
	Save(values ...*model.Kabupaten) error
	First() (*model.Kabupaten, error)
	Take() (*model.Kabupaten, error)
	Last() (*model.Kabupaten, error)
	Find() ([]*model.Kabupaten, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Kabupaten, err error)
	FindInBatches(result *[]*model.Kabupaten, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Kabupaten) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKabupatenDo
	Assign(attrs ...field.AssignExpr) IKabupatenDo
	Joins(fields ...field.RelationField) IKabupatenDo
	Preload(fields ...field.RelationField) IKabupatenDo
	FirstOrInit() (*model.Kabupaten, error)
	FirstOrCreate() (*model.Kabupaten, error)
	FindByPage(offset int, limit int) (result []*model.Kabupaten, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKabupatenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k kabupatenDo) Debug() IKabupatenDo {
	return k.withDO(k.DO.Debug())
}

func (k kabupatenDo) WithContext(ctx context.Context) IKabupatenDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kabupatenDo) ReadDB() IKabupatenDo {
	return k.Clauses(dbresolver.Read)
}

func (k kabupatenDo) WriteDB() IKabupatenDo {
	return k.Clauses(dbresolver.Write)
}

func (k kabupatenDo) Session(config *gorm.Session) IKabupatenDo {
	return k.withDO(k.DO.Session(config))
}

func (k kabupatenDo) Clauses(conds ...clause.Expression) IKabupatenDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kabupatenDo) Returning(value interface{}, columns ...string) IKabupatenDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kabupatenDo) Not(conds ...gen.Condition) IKabupatenDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kabupatenDo) Or(conds ...gen.Condition) IKabupatenDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kabupatenDo) Select(conds ...field.Expr) IKabupatenDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kabupatenDo) Where(conds ...gen.Condition) IKabupatenDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kabupatenDo) Order(conds ...field.Expr) IKabupatenDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kabupatenDo) Distinct(cols ...field.Expr) IKabupatenDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kabupatenDo) Omit(cols ...field.Expr) IKabupatenDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kabupatenDo) Join(table schema.Tabler, on ...field.Expr) IKabupatenDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kabupatenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKabupatenDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kabupatenDo) RightJoin(table schema.Tabler, on ...field.Expr) IKabupatenDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kabupatenDo) Group(cols ...field.Expr) IKabupatenDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kabupatenDo) Having(conds ...gen.Condition) IKabupatenDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kabupatenDo) Limit(limit int) IKabupatenDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kabupatenDo) Offset(offset int) IKabupatenDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kabupatenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKabupatenDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kabupatenDo) Unscoped() IKabupatenDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kabupatenDo) Create(values ...*model.Kabupaten) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kabupatenDo) CreateInBatches(values []*model.Kabupaten, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kabupatenDo) Save(values ...*model.Kabupaten) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kabupatenDo) First() (*model.Kabupaten, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kabupaten), nil
	}
}

func (k kabupatenDo) Take() (*model.Kabupaten, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kabupaten), nil
	}
}

func (k kabupatenDo) Last() (*model.Kabupaten, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kabupaten), nil
	}
}

func (k kabupatenDo) Find() ([]*model.Kabupaten, error) {
	result, err := k.DO.Find()
	return result.([]*model.Kabupaten), err
}

func (k kabupatenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Kabupaten, err error) {
	buf := make([]*model.Kabupaten, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kabupatenDo) FindInBatches(result *[]*model.Kabupaten, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kabupatenDo) Attrs(attrs ...field.AssignExpr) IKabupatenDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kabupatenDo) Assign(attrs ...field.AssignExpr) IKabupatenDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kabupatenDo) Joins(fields ...field.RelationField) IKabupatenDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kabupatenDo) Preload(fields ...field.RelationField) IKabupatenDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kabupatenDo) FirstOrInit() (*model.Kabupaten, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kabupaten), nil
	}
}

func (k kabupatenDo) FirstOrCreate() (*model.Kabupaten, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kabupaten), nil
	}
}

func (k kabupatenDo) FindByPage(offset int, limit int) (result []*model.Kabupaten, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kabupatenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kabupatenDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kabupatenDo) Delete(models ...*model.Kabupaten) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kabupatenDo) withDO(do gen.Dao) *kabupatenDo {
	k.DO = *do.(*gen.DO)
	return k
}
