// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newKelurahan(db *gorm.DB, opts ...gen.DOOption) kelurahan {
	_kelurahan := kelurahan{}

	_kelurahan.kelurahanDo.UseDB(db, opts...)
	_kelurahan.kelurahanDo.UseModel(&model.Kelurahan{})

	tableName := _kelurahan.kelurahanDo.TableName()
	_kelurahan.ALL = field.NewAsterisk(tableName)
	_kelurahan.KelID = field.NewInt64(tableName, "kel_id")
	_kelurahan.KelName = field.NewString(tableName, "kel_name")
	_kelurahan.KecID = field.NewInt64(tableName, "kec_id")

	_kelurahan.fillFieldMap()

	return _kelurahan
}

type kelurahan struct {
	kelurahanDo

	ALL     field.Asterisk
	KelID   field.Int64
	KelName field.String
	KecID   field.Int64

	fieldMap map[string]field.Expr
}

func (k kelurahan) Table(newTableName string) *kelurahan {
	k.kelurahanDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kelurahan) As(alias string) *kelurahan {
	k.kelurahanDo.DO = *(k.kelurahanDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kelurahan) updateTableName(table string) *kelurahan {
	k.ALL = field.NewAsterisk(table)
	k.KelID = field.NewInt64(table, "kel_id")
	k.KelName = field.NewString(table, "kel_name")
	k.KecID = field.NewInt64(table, "kec_id")

	k.fillFieldMap()

	return k
}

func (k *kelurahan) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kelurahan) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 3)
	k.fieldMap["kel_id"] = k.KelID
	k.fieldMap["kel_name"] = k.KelName
	k.fieldMap["kec_id"] = k.KecID
}

func (k kelurahan) clone(db *gorm.DB) kelurahan {
	k.kelurahanDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kelurahan) replaceDB(db *gorm.DB) kelurahan {
	k.kelurahanDo.ReplaceDB(db)
	return k
}

type kelurahanDo struct{ gen.DO }

type IKelurahanDo interface {
	gen.SubQuery
	Debug() IKelurahanDo
	WithContext(ctx context.Context) IKelurahanDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKelurahanDo
	WriteDB() IKelurahanDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKelurahanDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKelurahanDo
	Not(conds ...gen.Condition) IKelurahanDo
	Or(conds ...gen.Condition) IKelurahanDo
	Select(conds ...field.Expr) IKelurahanDo
	Where(conds ...gen.Condition) IKelurahanDo
	Order(conds ...field.Expr) IKelurahanDo
	Distinct(cols ...field.Expr) IKelurahanDo
	Omit(cols ...field.Expr) IKelurahanDo
	Join(table schema.Tabler, on ...field.Expr) IKelurahanDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKelurahanDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKelurahanDo
	Group(cols ...field.Expr) IKelurahanDo
	Having(conds ...gen.Condition) IKelurahanDo
	Limit(limit int) IKelurahanDo
	Offset(offset int) IKelurahanDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKelurahanDo
	Unscoped() IKelurahanDo
	Create(values ...*model.Kelurahan) error
	CreateInBatches(values []*model.Kelurahan, batchSize int) error
	Save(values ...*model.Kelurahan) error
	First() (*model.Kelurahan, error)
	Take() (*model.Kelurahan, error)
	Last() (*model.Kelurahan, error)
	Find() ([]*model.Kelurahan, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Kelurahan, err error)
	FindInBatches(result *[]*model.Kelurahan, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Kelurahan) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKelurahanDo
	Assign(attrs ...field.AssignExpr) IKelurahanDo
	Joins(fields ...field.RelationField) IKelurahanDo
	Preload(fields ...field.RelationField) IKelurahanDo
	FirstOrInit() (*model.Kelurahan, error)
	FirstOrCreate() (*model.Kelurahan, error)
	FindByPage(offset int, limit int) (result []*model.Kelurahan, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKelurahanDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k kelurahanDo) Debug() IKelurahanDo {
	return k.withDO(k.DO.Debug())
}

func (k kelurahanDo) WithContext(ctx context.Context) IKelurahanDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kelurahanDo) ReadDB() IKelurahanDo {
	return k.Clauses(dbresolver.Read)
}

func (k kelurahanDo) WriteDB() IKelurahanDo {
	return k.Clauses(dbresolver.Write)
}

func (k kelurahanDo) Session(config *gorm.Session) IKelurahanDo {
	return k.withDO(k.DO.Session(config))
}

func (k kelurahanDo) Clauses(conds ...clause.Expression) IKelurahanDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kelurahanDo) Returning(value interface{}, columns ...string) IKelurahanDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kelurahanDo) Not(conds ...gen.Condition) IKelurahanDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kelurahanDo) Or(conds ...gen.Condition) IKelurahanDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kelurahanDo) Select(conds ...field.Expr) IKelurahanDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kelurahanDo) Where(conds ...gen.Condition) IKelurahanDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kelurahanDo) Order(conds ...field.Expr) IKelurahanDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kelurahanDo) Distinct(cols ...field.Expr) IKelurahanDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kelurahanDo) Omit(cols ...field.Expr) IKelurahanDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kelurahanDo) Join(table schema.Tabler, on ...field.Expr) IKelurahanDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kelurahanDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKelurahanDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kelurahanDo) RightJoin(table schema.Tabler, on ...field.Expr) IKelurahanDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kelurahanDo) Group(cols ...field.Expr) IKelurahanDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kelurahanDo) Having(conds ...gen.Condition) IKelurahanDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kelurahanDo) Limit(limit int) IKelurahanDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kelurahanDo) Offset(offset int) IKelurahanDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kelurahanDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKelurahanDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kelurahanDo) Unscoped() IKelurahanDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kelurahanDo) Create(values ...*model.Kelurahan) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kelurahanDo) CreateInBatches(values []*model.Kelurahan, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kelurahanDo) Save(values ...*model.Kelurahan) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kelurahanDo) First() (*model.Kelurahan, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kelurahan), nil
	}
}

func (k kelurahanDo) Take() (*model.Kelurahan, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kelurahan), nil
	}
}

func (k kelurahanDo) Last() (*model.Kelurahan, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kelurahan), nil
	}
}

func (k kelurahanDo) Find() ([]*model.Kelurahan, error) {
	result, err := k.DO.Find()
	return result.([]*model.Kelurahan), err
}

func (k kelurahanDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Kelurahan, err error) {
	buf := make([]*model.Kelurahan, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kelurahanDo) FindInBatches(result *[]*model.Kelurahan, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kelurahanDo) Attrs(attrs ...field.AssignExpr) IKelurahanDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kelurahanDo) Assign(attrs ...field.AssignExpr) IKelurahanDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kelurahanDo) Joins(fields ...field.RelationField) IKelurahanDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kelurahanDo) Preload(fields ...field.RelationField) IKelurahanDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kelurahanDo) FirstOrInit() (*model.Kelurahan, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kelurahan), nil
	}
}

func (k kelurahanDo) FirstOrCreate() (*model.Kelurahan, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kelurahan), nil
	}
}

func (k kelurahanDo) FindByPage(offset int, limit int) (result []*model.Kelurahan, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kelurahanDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kelurahanDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kelurahanDo) Delete(models ...*model.Kelurahan) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kelurahanDo) withDO(do gen.Dao) *kelurahanDo {
	k.DO = *do.(*gen.DO)
	return k
}
