// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newLeasingContractDocument(db *gorm.DB, opts ...gen.DOOption) leasingContractDocument {
	_leasingContractDocument := leasingContractDocument{}

	_leasingContractDocument.leasingContractDocumentDo.UseDB(db, opts...)
	_leasingContractDocument.leasingContractDocumentDo.UseModel(&model.LeasingContractDocument{})

	tableName := _leasingContractDocument.leasingContractDocumentDo.TableName()
	_leasingContractDocument.ALL = field.NewAsterisk(tableName)
	_leasingContractDocument.LdocID = field.NewInt64(tableName, "ldoc_id")
	_leasingContractDocument.FileName = field.NewString(tableName, "file_name")
	_leasingContractDocument.FileSize = field.NewFloat64(tableName, "file_size")
	_leasingContractDocument.FileType = field.NewString(tableName, "file_type")
	_leasingContractDocument.FileURL = field.NewString(tableName, "file_url")
	_leasingContractDocument.ContractID = field.NewInt64(tableName, "contract_id")
	_leasingContractDocument.CreatedAt = field.NewTime(tableName, "created_at")

	_leasingContractDocument.fillFieldMap()

	return _leasingContractDocument
}

type leasingContractDocument struct {
	leasingContractDocumentDo

	ALL        field.Asterisk
	LdocID     field.Int64
	FileName   field.String
	FileSize   field.Float64
	FileType   field.String
	FileURL    field.String
	ContractID field.Int64
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (l leasingContractDocument) Table(newTableName string) *leasingContractDocument {
	l.leasingContractDocumentDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingContractDocument) As(alias string) *leasingContractDocument {
	l.leasingContractDocumentDo.DO = *(l.leasingContractDocumentDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingContractDocument) updateTableName(table string) *leasingContractDocument {
	l.ALL = field.NewAsterisk(table)
	l.LdocID = field.NewInt64(table, "ldoc_id")
	l.FileName = field.NewString(table, "file_name")
	l.FileSize = field.NewFloat64(table, "file_size")
	l.FileType = field.NewString(table, "file_type")
	l.FileURL = field.NewString(table, "file_url")
	l.ContractID = field.NewInt64(table, "contract_id")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *leasingContractDocument) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingContractDocument) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 7)
	l.fieldMap["ldoc_id"] = l.LdocID
	l.fieldMap["file_name"] = l.FileName
	l.fieldMap["file_size"] = l.FileSize
	l.fieldMap["file_type"] = l.FileType
	l.fieldMap["file_url"] = l.FileURL
	l.fieldMap["contract_id"] = l.ContractID
	l.fieldMap["created_at"] = l.CreatedAt
}

func (l leasingContractDocument) clone(db *gorm.DB) leasingContractDocument {
	l.leasingContractDocumentDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l leasingContractDocument) replaceDB(db *gorm.DB) leasingContractDocument {
	l.leasingContractDocumentDo.ReplaceDB(db)
	return l
}

type leasingContractDocumentDo struct{ gen.DO }

type ILeasingContractDocumentDo interface {
	gen.SubQuery
	Debug() ILeasingContractDocumentDo
	WithContext(ctx context.Context) ILeasingContractDocumentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingContractDocumentDo
	WriteDB() ILeasingContractDocumentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingContractDocumentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingContractDocumentDo
	Not(conds ...gen.Condition) ILeasingContractDocumentDo
	Or(conds ...gen.Condition) ILeasingContractDocumentDo
	Select(conds ...field.Expr) ILeasingContractDocumentDo
	Where(conds ...gen.Condition) ILeasingContractDocumentDo
	Order(conds ...field.Expr) ILeasingContractDocumentDo
	Distinct(cols ...field.Expr) ILeasingContractDocumentDo
	Omit(cols ...field.Expr) ILeasingContractDocumentDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo
	Group(cols ...field.Expr) ILeasingContractDocumentDo
	Having(conds ...gen.Condition) ILeasingContractDocumentDo
	Limit(limit int) ILeasingContractDocumentDo
	Offset(offset int) ILeasingContractDocumentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingContractDocumentDo
	Unscoped() ILeasingContractDocumentDo
	Create(values ...*model.LeasingContractDocument) error
	CreateInBatches(values []*model.LeasingContractDocument, batchSize int) error
	Save(values ...*model.LeasingContractDocument) error
	First() (*model.LeasingContractDocument, error)
	Take() (*model.LeasingContractDocument, error)
	Last() (*model.LeasingContractDocument, error)
	Find() ([]*model.LeasingContractDocument, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LeasingContractDocument, err error)
	FindInBatches(result *[]*model.LeasingContractDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LeasingContractDocument) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingContractDocumentDo
	Assign(attrs ...field.AssignExpr) ILeasingContractDocumentDo
	Joins(fields ...field.RelationField) ILeasingContractDocumentDo
	Preload(fields ...field.RelationField) ILeasingContractDocumentDo
	FirstOrInit() (*model.LeasingContractDocument, error)
	FirstOrCreate() (*model.LeasingContractDocument, error)
	FindByPage(offset int, limit int) (result []*model.LeasingContractDocument, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingContractDocumentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingContractDocumentDo) Debug() ILeasingContractDocumentDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingContractDocumentDo) WithContext(ctx context.Context) ILeasingContractDocumentDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingContractDocumentDo) ReadDB() ILeasingContractDocumentDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingContractDocumentDo) WriteDB() ILeasingContractDocumentDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingContractDocumentDo) Session(config *gorm.Session) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingContractDocumentDo) Clauses(conds ...clause.Expression) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingContractDocumentDo) Returning(value interface{}, columns ...string) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingContractDocumentDo) Not(conds ...gen.Condition) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingContractDocumentDo) Or(conds ...gen.Condition) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingContractDocumentDo) Select(conds ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingContractDocumentDo) Where(conds ...gen.Condition) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingContractDocumentDo) Order(conds ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingContractDocumentDo) Distinct(cols ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingContractDocumentDo) Omit(cols ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingContractDocumentDo) Join(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingContractDocumentDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingContractDocumentDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingContractDocumentDo) Group(cols ...field.Expr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingContractDocumentDo) Having(conds ...gen.Condition) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingContractDocumentDo) Limit(limit int) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingContractDocumentDo) Offset(offset int) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingContractDocumentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingContractDocumentDo) Unscoped() ILeasingContractDocumentDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingContractDocumentDo) Create(values ...*model.LeasingContractDocument) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingContractDocumentDo) CreateInBatches(values []*model.LeasingContractDocument, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingContractDocumentDo) Save(values ...*model.LeasingContractDocument) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingContractDocumentDo) First() (*model.LeasingContractDocument, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) Take() (*model.LeasingContractDocument, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) Last() (*model.LeasingContractDocument, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) Find() ([]*model.LeasingContractDocument, error) {
	result, err := l.DO.Find()
	return result.([]*model.LeasingContractDocument), err
}

func (l leasingContractDocumentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LeasingContractDocument, err error) {
	buf := make([]*model.LeasingContractDocument, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingContractDocumentDo) FindInBatches(result *[]*model.LeasingContractDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingContractDocumentDo) Attrs(attrs ...field.AssignExpr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingContractDocumentDo) Assign(attrs ...field.AssignExpr) ILeasingContractDocumentDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingContractDocumentDo) Joins(fields ...field.RelationField) ILeasingContractDocumentDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingContractDocumentDo) Preload(fields ...field.RelationField) ILeasingContractDocumentDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingContractDocumentDo) FirstOrInit() (*model.LeasingContractDocument, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) FirstOrCreate() (*model.LeasingContractDocument, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContractDocument), nil
	}
}

func (l leasingContractDocumentDo) FindByPage(offset int, limit int) (result []*model.LeasingContractDocument, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingContractDocumentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingContractDocumentDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingContractDocumentDo) Delete(models ...*model.LeasingContractDocument) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingContractDocumentDo) withDO(do gen.Dao) *leasingContractDocumentDo {
	l.DO = *do.(*gen.DO)
	return l
}
