// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newLeasingContract(db *gorm.DB, opts ...gen.DOOption) leasingContract {
	_leasingContract := leasingContract{}

	_leasingContract.leasingContractDo.UseDB(db, opts...)
	_leasingContract.leasingContractDo.UseModel(&model.LeasingContract{})

	tableName := _leasingContract.leasingContractDo.TableName()
	_leasingContract.ALL = field.NewAsterisk(tableName)
	_leasingContract.ContractID = field.NewInt64(tableName, "contract_id")
	_leasingContract.ContractNumber = field.NewString(tableName, "contract_number")
	_leasingContract.RequestDate = field.NewTime(tableName, "request_date")
	_leasingContract.TanggalAkad = field.NewTime(tableName, "tanggal_akad")
	_leasingContract.TanggalMulaiCicil = field.NewTime(tableName, "tanggal_mulai_cicil")
	_leasingContract.TenorBulan = field.NewInt16(tableName, "tenor_bulan")
	_leasingContract.NilaiKendaraan = field.NewFloat64(tableName, "nilai_kendaraan")
	_leasingContract.DpDibayar = field.NewFloat64(tableName, "dp_dibayar")
	_leasingContract.PokokPinjaman = field.NewFloat64(tableName, "pokok_pinjaman")
	_leasingContract.TotalPinjaman = field.NewFloat64(tableName, "total_pinjaman")
	_leasingContract.CicilanPerBulan = field.NewFloat64(tableName, "cicilan_per_bulan")
	_leasingContract.Status = field.NewString(tableName, "status")
	_leasingContract.CreatedAt = field.NewTime(tableName, "created_at")
	_leasingContract.UpdatedAt = field.NewTime(tableName, "updated_at")
	_leasingContract.CustomerID = field.NewInt64(tableName, "customer_id")
	_leasingContract.MotorID = field.NewInt64(tableName, "motor_id")
	_leasingContract.ProductID = field.NewInt64(tableName, "product_id")

	_leasingContract.fillFieldMap()

	return _leasingContract
}

type leasingContract struct {
	leasingContractDo

	ALL               field.Asterisk
	ContractID        field.Int64
	ContractNumber    field.String
	RequestDate       field.Time
	TanggalAkad       field.Time
	TanggalMulaiCicil field.Time
	TenorBulan        field.Int16
	NilaiKendaraan    field.Float64
	DpDibayar         field.Float64
	PokokPinjaman     field.Float64
	TotalPinjaman     field.Float64
	CicilanPerBulan   field.Float64
	Status            field.String
	CreatedAt         field.Time
	UpdatedAt         field.Time
	CustomerID        field.Int64
	MotorID           field.Int64
	ProductID         field.Int64

	fieldMap map[string]field.Expr
}

func (l leasingContract) Table(newTableName string) *leasingContract {
	l.leasingContractDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingContract) As(alias string) *leasingContract {
	l.leasingContractDo.DO = *(l.leasingContractDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingContract) updateTableName(table string) *leasingContract {
	l.ALL = field.NewAsterisk(table)
	l.ContractID = field.NewInt64(table, "contract_id")
	l.ContractNumber = field.NewString(table, "contract_number")
	l.RequestDate = field.NewTime(table, "request_date")
	l.TanggalAkad = field.NewTime(table, "tanggal_akad")
	l.TanggalMulaiCicil = field.NewTime(table, "tanggal_mulai_cicil")
	l.TenorBulan = field.NewInt16(table, "tenor_bulan")
	l.NilaiKendaraan = field.NewFloat64(table, "nilai_kendaraan")
	l.DpDibayar = field.NewFloat64(table, "dp_dibayar")
	l.PokokPinjaman = field.NewFloat64(table, "pokok_pinjaman")
	l.TotalPinjaman = field.NewFloat64(table, "total_pinjaman")
	l.CicilanPerBulan = field.NewFloat64(table, "cicilan_per_bulan")
	l.Status = field.NewString(table, "status")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")
	l.CustomerID = field.NewInt64(table, "customer_id")
	l.MotorID = field.NewInt64(table, "motor_id")
	l.ProductID = field.NewInt64(table, "product_id")

	l.fillFieldMap()

	return l
}

func (l *leasingContract) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingContract) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 17)
	l.fieldMap["contract_id"] = l.ContractID
	l.fieldMap["contract_number"] = l.ContractNumber
	l.fieldMap["request_date"] = l.RequestDate
	l.fieldMap["tanggal_akad"] = l.TanggalAkad
	l.fieldMap["tanggal_mulai_cicil"] = l.TanggalMulaiCicil
	l.fieldMap["tenor_bulan"] = l.TenorBulan
	l.fieldMap["nilai_kendaraan"] = l.NilaiKendaraan
	l.fieldMap["dp_dibayar"] = l.DpDibayar
	l.fieldMap["pokok_pinjaman"] = l.PokokPinjaman
	l.fieldMap["total_pinjaman"] = l.TotalPinjaman
	l.fieldMap["cicilan_per_bulan"] = l.CicilanPerBulan
	l.fieldMap["status"] = l.Status
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
	l.fieldMap["customer_id"] = l.CustomerID
	l.fieldMap["motor_id"] = l.MotorID
	l.fieldMap["product_id"] = l.ProductID
}

func (l leasingContract) clone(db *gorm.DB) leasingContract {
	l.leasingContractDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l leasingContract) replaceDB(db *gorm.DB) leasingContract {
	l.leasingContractDo.ReplaceDB(db)
	return l
}

type leasingContractDo struct{ gen.DO }

type ILeasingContractDo interface {
	gen.SubQuery
	Debug() ILeasingContractDo
	WithContext(ctx context.Context) ILeasingContractDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingContractDo
	WriteDB() ILeasingContractDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingContractDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingContractDo
	Not(conds ...gen.Condition) ILeasingContractDo
	Or(conds ...gen.Condition) ILeasingContractDo
	Select(conds ...field.Expr) ILeasingContractDo
	Where(conds ...gen.Condition) ILeasingContractDo
	Order(conds ...field.Expr) ILeasingContractDo
	Distinct(cols ...field.Expr) ILeasingContractDo
	Omit(cols ...field.Expr) ILeasingContractDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingContractDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDo
	Group(cols ...field.Expr) ILeasingContractDo
	Having(conds ...gen.Condition) ILeasingContractDo
	Limit(limit int) ILeasingContractDo
	Offset(offset int) ILeasingContractDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingContractDo
	Unscoped() ILeasingContractDo
	Create(values ...*model.LeasingContract) error
	CreateInBatches(values []*model.LeasingContract, batchSize int) error
	Save(values ...*model.LeasingContract) error
	First() (*model.LeasingContract, error)
	Take() (*model.LeasingContract, error)
	Last() (*model.LeasingContract, error)
	Find() ([]*model.LeasingContract, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LeasingContract, err error)
	FindInBatches(result *[]*model.LeasingContract, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LeasingContract) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingContractDo
	Assign(attrs ...field.AssignExpr) ILeasingContractDo
	Joins(fields ...field.RelationField) ILeasingContractDo
	Preload(fields ...field.RelationField) ILeasingContractDo
	FirstOrInit() (*model.LeasingContract, error)
	FirstOrCreate() (*model.LeasingContract, error)
	FindByPage(offset int, limit int) (result []*model.LeasingContract, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingContractDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingContractDo) Debug() ILeasingContractDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingContractDo) WithContext(ctx context.Context) ILeasingContractDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingContractDo) ReadDB() ILeasingContractDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingContractDo) WriteDB() ILeasingContractDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingContractDo) Session(config *gorm.Session) ILeasingContractDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingContractDo) Clauses(conds ...clause.Expression) ILeasingContractDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingContractDo) Returning(value interface{}, columns ...string) ILeasingContractDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingContractDo) Not(conds ...gen.Condition) ILeasingContractDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingContractDo) Or(conds ...gen.Condition) ILeasingContractDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingContractDo) Select(conds ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingContractDo) Where(conds ...gen.Condition) ILeasingContractDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingContractDo) Order(conds ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingContractDo) Distinct(cols ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingContractDo) Omit(cols ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingContractDo) Join(table schema.Tabler, on ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingContractDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingContractDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingContractDo) Group(cols ...field.Expr) ILeasingContractDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingContractDo) Having(conds ...gen.Condition) ILeasingContractDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingContractDo) Limit(limit int) ILeasingContractDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingContractDo) Offset(offset int) ILeasingContractDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingContractDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingContractDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingContractDo) Unscoped() ILeasingContractDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingContractDo) Create(values ...*model.LeasingContract) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingContractDo) CreateInBatches(values []*model.LeasingContract, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingContractDo) Save(values ...*model.LeasingContract) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingContractDo) First() (*model.LeasingContract, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContract), nil
	}
}

func (l leasingContractDo) Take() (*model.LeasingContract, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContract), nil
	}
}

func (l leasingContractDo) Last() (*model.LeasingContract, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContract), nil
	}
}

func (l leasingContractDo) Find() ([]*model.LeasingContract, error) {
	result, err := l.DO.Find()
	return result.([]*model.LeasingContract), err
}

func (l leasingContractDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LeasingContract, err error) {
	buf := make([]*model.LeasingContract, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingContractDo) FindInBatches(result *[]*model.LeasingContract, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingContractDo) Attrs(attrs ...field.AssignExpr) ILeasingContractDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingContractDo) Assign(attrs ...field.AssignExpr) ILeasingContractDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingContractDo) Joins(fields ...field.RelationField) ILeasingContractDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingContractDo) Preload(fields ...field.RelationField) ILeasingContractDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingContractDo) FirstOrInit() (*model.LeasingContract, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContract), nil
	}
}

func (l leasingContractDo) FirstOrCreate() (*model.LeasingContract, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingContract), nil
	}
}

func (l leasingContractDo) FindByPage(offset int, limit int) (result []*model.LeasingContract, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingContractDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingContractDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingContractDo) Delete(models ...*model.LeasingContract) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingContractDo) withDO(do gen.Dao) *leasingContractDo {
	l.DO = *do.(*gen.DO)
	return l
}
