// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newLeasingTask(db *gorm.DB, opts ...gen.DOOption) leasingTask {
	_leasingTask := leasingTask{}

	_leasingTask.leasingTaskDo.UseDB(db, opts...)
	_leasingTask.leasingTaskDo.UseModel(&model.LeasingTask{})

	tableName := _leasingTask.leasingTaskDo.TableName()
	_leasingTask.ALL = field.NewAsterisk(tableName)
	_leasingTask.TaskID = field.NewInt64(tableName, "task_id")
	_leasingTask.TaskName = field.NewString(tableName, "task_name")
	_leasingTask.Startdate = field.NewTime(tableName, "startdate")
	_leasingTask.Enddate = field.NewTime(tableName, "enddate")
	_leasingTask.ActualStartdate = field.NewTime(tableName, "actual_startdate")
	_leasingTask.ActualEnddate = field.NewTime(tableName, "actual_enddate")
	_leasingTask.Status = field.NewString(tableName, "status")
	_leasingTask.ContractID = field.NewInt64(tableName, "contract_id")
	_leasingTask.RoleID = field.NewInt64(tableName, "role_id")
	_leasingTask.CreatedAt = field.NewTime(tableName, "created_at")
	_leasingTask.SequenceNo = field.NewInt16(tableName, "sequence_no")
	_leasingTask.CallFunction = field.NewString(tableName, "call_function")

	_leasingTask.fillFieldMap()

	return _leasingTask
}

type leasingTask struct {
	leasingTaskDo

	ALL             field.Asterisk
	TaskID          field.Int64
	TaskName        field.String
	Startdate       field.Time
	Enddate         field.Time
	ActualStartdate field.Time
	ActualEnddate   field.Time
	Status          field.String
	ContractID      field.Int64
	RoleID          field.Int64
	CreatedAt       field.Time
	SequenceNo      field.Int16
	CallFunction    field.String

	fieldMap map[string]field.Expr
}

func (l leasingTask) Table(newTableName string) *leasingTask {
	l.leasingTaskDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingTask) As(alias string) *leasingTask {
	l.leasingTaskDo.DO = *(l.leasingTaskDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingTask) updateTableName(table string) *leasingTask {
	l.ALL = field.NewAsterisk(table)
	l.TaskID = field.NewInt64(table, "task_id")
	l.TaskName = field.NewString(table, "task_name")
	l.Startdate = field.NewTime(table, "startdate")
	l.Enddate = field.NewTime(table, "enddate")
	l.ActualStartdate = field.NewTime(table, "actual_startdate")
	l.ActualEnddate = field.NewTime(table, "actual_enddate")
	l.Status = field.NewString(table, "status")
	l.ContractID = field.NewInt64(table, "contract_id")
	l.RoleID = field.NewInt64(table, "role_id")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.SequenceNo = field.NewInt16(table, "sequence_no")
	l.CallFunction = field.NewString(table, "call_function")

	l.fillFieldMap()

	return l
}

func (l *leasingTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingTask) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 12)
	l.fieldMap["task_id"] = l.TaskID
	l.fieldMap["task_name"] = l.TaskName
	l.fieldMap["startdate"] = l.Startdate
	l.fieldMap["enddate"] = l.Enddate
	l.fieldMap["actual_startdate"] = l.ActualStartdate
	l.fieldMap["actual_enddate"] = l.ActualEnddate
	l.fieldMap["status"] = l.Status
	l.fieldMap["contract_id"] = l.ContractID
	l.fieldMap["role_id"] = l.RoleID
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["sequence_no"] = l.SequenceNo
	l.fieldMap["call_function"] = l.CallFunction
}

func (l leasingTask) clone(db *gorm.DB) leasingTask {
	l.leasingTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l leasingTask) replaceDB(db *gorm.DB) leasingTask {
	l.leasingTaskDo.ReplaceDB(db)
	return l
}

type leasingTaskDo struct{ gen.DO }

type ILeasingTaskDo interface {
	gen.SubQuery
	Debug() ILeasingTaskDo
	WithContext(ctx context.Context) ILeasingTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingTaskDo
	WriteDB() ILeasingTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingTaskDo
	Not(conds ...gen.Condition) ILeasingTaskDo
	Or(conds ...gen.Condition) ILeasingTaskDo
	Select(conds ...field.Expr) ILeasingTaskDo
	Where(conds ...gen.Condition) ILeasingTaskDo
	Order(conds ...field.Expr) ILeasingTaskDo
	Distinct(cols ...field.Expr) ILeasingTaskDo
	Omit(cols ...field.Expr) ILeasingTaskDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskDo
	Group(cols ...field.Expr) ILeasingTaskDo
	Having(conds ...gen.Condition) ILeasingTaskDo
	Limit(limit int) ILeasingTaskDo
	Offset(offset int) ILeasingTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTaskDo
	Unscoped() ILeasingTaskDo
	Create(values ...*model.LeasingTask) error
	CreateInBatches(values []*model.LeasingTask, batchSize int) error
	Save(values ...*model.LeasingTask) error
	First() (*model.LeasingTask, error)
	Take() (*model.LeasingTask, error)
	Last() (*model.LeasingTask, error)
	Find() ([]*model.LeasingTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LeasingTask, err error)
	FindInBatches(result *[]*model.LeasingTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LeasingTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingTaskDo
	Assign(attrs ...field.AssignExpr) ILeasingTaskDo
	Joins(fields ...field.RelationField) ILeasingTaskDo
	Preload(fields ...field.RelationField) ILeasingTaskDo
	FirstOrInit() (*model.LeasingTask, error)
	FirstOrCreate() (*model.LeasingTask, error)
	FindByPage(offset int, limit int) (result []*model.LeasingTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingTaskDo) Debug() ILeasingTaskDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingTaskDo) WithContext(ctx context.Context) ILeasingTaskDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingTaskDo) ReadDB() ILeasingTaskDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingTaskDo) WriteDB() ILeasingTaskDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingTaskDo) Session(config *gorm.Session) ILeasingTaskDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingTaskDo) Clauses(conds ...clause.Expression) ILeasingTaskDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingTaskDo) Returning(value interface{}, columns ...string) ILeasingTaskDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingTaskDo) Not(conds ...gen.Condition) ILeasingTaskDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingTaskDo) Or(conds ...gen.Condition) ILeasingTaskDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingTaskDo) Select(conds ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingTaskDo) Where(conds ...gen.Condition) ILeasingTaskDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingTaskDo) Order(conds ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingTaskDo) Distinct(cols ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingTaskDo) Omit(cols ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingTaskDo) Join(table schema.Tabler, on ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingTaskDo) Group(cols ...field.Expr) ILeasingTaskDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingTaskDo) Having(conds ...gen.Condition) ILeasingTaskDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingTaskDo) Limit(limit int) ILeasingTaskDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingTaskDo) Offset(offset int) ILeasingTaskDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTaskDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingTaskDo) Unscoped() ILeasingTaskDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingTaskDo) Create(values ...*model.LeasingTask) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingTaskDo) CreateInBatches(values []*model.LeasingTask, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingTaskDo) Save(values ...*model.LeasingTask) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingTaskDo) First() (*model.LeasingTask, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTask), nil
	}
}

func (l leasingTaskDo) Take() (*model.LeasingTask, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTask), nil
	}
}

func (l leasingTaskDo) Last() (*model.LeasingTask, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTask), nil
	}
}

func (l leasingTaskDo) Find() ([]*model.LeasingTask, error) {
	result, err := l.DO.Find()
	return result.([]*model.LeasingTask), err
}

func (l leasingTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LeasingTask, err error) {
	buf := make([]*model.LeasingTask, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingTaskDo) FindInBatches(result *[]*model.LeasingTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingTaskDo) Attrs(attrs ...field.AssignExpr) ILeasingTaskDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingTaskDo) Assign(attrs ...field.AssignExpr) ILeasingTaskDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingTaskDo) Joins(fields ...field.RelationField) ILeasingTaskDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingTaskDo) Preload(fields ...field.RelationField) ILeasingTaskDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingTaskDo) FirstOrInit() (*model.LeasingTask, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTask), nil
	}
}

func (l leasingTaskDo) FirstOrCreate() (*model.LeasingTask, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTask), nil
	}
}

func (l leasingTaskDo) FindByPage(offset int, limit int) (result []*model.LeasingTask, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingTaskDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingTaskDo) Delete(models ...*model.LeasingTask) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingTaskDo) withDO(do gen.Dao) *leasingTaskDo {
	l.DO = *do.(*gen.DO)
	return l
}
