// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newLeasingTasksAttribute(db *gorm.DB, opts ...gen.DOOption) leasingTasksAttribute {
	_leasingTasksAttribute := leasingTasksAttribute{}

	_leasingTasksAttribute.leasingTasksAttributeDo.UseDB(db, opts...)
	_leasingTasksAttribute.leasingTasksAttributeDo.UseModel(&model.LeasingTasksAttribute{})

	tableName := _leasingTasksAttribute.leasingTasksAttributeDo.TableName()
	_leasingTasksAttribute.ALL = field.NewAsterisk(tableName)
	_leasingTasksAttribute.TasaID = field.NewInt64(tableName, "tasa_id")
	_leasingTasksAttribute.TasaName = field.NewString(tableName, "tasa_name")
	_leasingTasksAttribute.TasaValue = field.NewString(tableName, "tasa_value")
	_leasingTasksAttribute.TasaStatus = field.NewString(tableName, "tasa_status")
	_leasingTasksAttribute.TasaTaskID = field.NewInt64(tableName, "tasa_task_id")
	_leasingTasksAttribute.CreatedAt = field.NewTime(tableName, "created_at")

	_leasingTasksAttribute.fillFieldMap()

	return _leasingTasksAttribute
}

type leasingTasksAttribute struct {
	leasingTasksAttributeDo

	ALL        field.Asterisk
	TasaID     field.Int64
	TasaName   field.String
	TasaValue  field.String
	TasaStatus field.String
	TasaTaskID field.Int64
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (l leasingTasksAttribute) Table(newTableName string) *leasingTasksAttribute {
	l.leasingTasksAttributeDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingTasksAttribute) As(alias string) *leasingTasksAttribute {
	l.leasingTasksAttributeDo.DO = *(l.leasingTasksAttributeDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingTasksAttribute) updateTableName(table string) *leasingTasksAttribute {
	l.ALL = field.NewAsterisk(table)
	l.TasaID = field.NewInt64(table, "tasa_id")
	l.TasaName = field.NewString(table, "tasa_name")
	l.TasaValue = field.NewString(table, "tasa_value")
	l.TasaStatus = field.NewString(table, "tasa_status")
	l.TasaTaskID = field.NewInt64(table, "tasa_task_id")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *leasingTasksAttribute) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingTasksAttribute) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 6)
	l.fieldMap["tasa_id"] = l.TasaID
	l.fieldMap["tasa_name"] = l.TasaName
	l.fieldMap["tasa_value"] = l.TasaValue
	l.fieldMap["tasa_status"] = l.TasaStatus
	l.fieldMap["tasa_task_id"] = l.TasaTaskID
	l.fieldMap["created_at"] = l.CreatedAt
}

func (l leasingTasksAttribute) clone(db *gorm.DB) leasingTasksAttribute {
	l.leasingTasksAttributeDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l leasingTasksAttribute) replaceDB(db *gorm.DB) leasingTasksAttribute {
	l.leasingTasksAttributeDo.ReplaceDB(db)
	return l
}

type leasingTasksAttributeDo struct{ gen.DO }

type ILeasingTasksAttributeDo interface {
	gen.SubQuery
	Debug() ILeasingTasksAttributeDo
	WithContext(ctx context.Context) ILeasingTasksAttributeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingTasksAttributeDo
	WriteDB() ILeasingTasksAttributeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingTasksAttributeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingTasksAttributeDo
	Not(conds ...gen.Condition) ILeasingTasksAttributeDo
	Or(conds ...gen.Condition) ILeasingTasksAttributeDo
	Select(conds ...field.Expr) ILeasingTasksAttributeDo
	Where(conds ...gen.Condition) ILeasingTasksAttributeDo
	Order(conds ...field.Expr) ILeasingTasksAttributeDo
	Distinct(cols ...field.Expr) ILeasingTasksAttributeDo
	Omit(cols ...field.Expr) ILeasingTasksAttributeDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingTasksAttributeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTasksAttributeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTasksAttributeDo
	Group(cols ...field.Expr) ILeasingTasksAttributeDo
	Having(conds ...gen.Condition) ILeasingTasksAttributeDo
	Limit(limit int) ILeasingTasksAttributeDo
	Offset(offset int) ILeasingTasksAttributeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTasksAttributeDo
	Unscoped() ILeasingTasksAttributeDo
	Create(values ...*model.LeasingTasksAttribute) error
	CreateInBatches(values []*model.LeasingTasksAttribute, batchSize int) error
	Save(values ...*model.LeasingTasksAttribute) error
	First() (*model.LeasingTasksAttribute, error)
	Take() (*model.LeasingTasksAttribute, error)
	Last() (*model.LeasingTasksAttribute, error)
	Find() ([]*model.LeasingTasksAttribute, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LeasingTasksAttribute, err error)
	FindInBatches(result *[]*model.LeasingTasksAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LeasingTasksAttribute) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingTasksAttributeDo
	Assign(attrs ...field.AssignExpr) ILeasingTasksAttributeDo
	Joins(fields ...field.RelationField) ILeasingTasksAttributeDo
	Preload(fields ...field.RelationField) ILeasingTasksAttributeDo
	FirstOrInit() (*model.LeasingTasksAttribute, error)
	FirstOrCreate() (*model.LeasingTasksAttribute, error)
	FindByPage(offset int, limit int) (result []*model.LeasingTasksAttribute, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingTasksAttributeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingTasksAttributeDo) Debug() ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingTasksAttributeDo) WithContext(ctx context.Context) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingTasksAttributeDo) ReadDB() ILeasingTasksAttributeDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingTasksAttributeDo) WriteDB() ILeasingTasksAttributeDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingTasksAttributeDo) Session(config *gorm.Session) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingTasksAttributeDo) Clauses(conds ...clause.Expression) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingTasksAttributeDo) Returning(value interface{}, columns ...string) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingTasksAttributeDo) Not(conds ...gen.Condition) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingTasksAttributeDo) Or(conds ...gen.Condition) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingTasksAttributeDo) Select(conds ...field.Expr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingTasksAttributeDo) Where(conds ...gen.Condition) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingTasksAttributeDo) Order(conds ...field.Expr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingTasksAttributeDo) Distinct(cols ...field.Expr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingTasksAttributeDo) Omit(cols ...field.Expr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingTasksAttributeDo) Join(table schema.Tabler, on ...field.Expr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingTasksAttributeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingTasksAttributeDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingTasksAttributeDo) Group(cols ...field.Expr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingTasksAttributeDo) Having(conds ...gen.Condition) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingTasksAttributeDo) Limit(limit int) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingTasksAttributeDo) Offset(offset int) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingTasksAttributeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingTasksAttributeDo) Unscoped() ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingTasksAttributeDo) Create(values ...*model.LeasingTasksAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingTasksAttributeDo) CreateInBatches(values []*model.LeasingTasksAttribute, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingTasksAttributeDo) Save(values ...*model.LeasingTasksAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingTasksAttributeDo) First() (*model.LeasingTasksAttribute, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTasksAttribute), nil
	}
}

func (l leasingTasksAttributeDo) Take() (*model.LeasingTasksAttribute, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTasksAttribute), nil
	}
}

func (l leasingTasksAttributeDo) Last() (*model.LeasingTasksAttribute, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTasksAttribute), nil
	}
}

func (l leasingTasksAttributeDo) Find() ([]*model.LeasingTasksAttribute, error) {
	result, err := l.DO.Find()
	return result.([]*model.LeasingTasksAttribute), err
}

func (l leasingTasksAttributeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LeasingTasksAttribute, err error) {
	buf := make([]*model.LeasingTasksAttribute, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingTasksAttributeDo) FindInBatches(result *[]*model.LeasingTasksAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingTasksAttributeDo) Attrs(attrs ...field.AssignExpr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingTasksAttributeDo) Assign(attrs ...field.AssignExpr) ILeasingTasksAttributeDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingTasksAttributeDo) Joins(fields ...field.RelationField) ILeasingTasksAttributeDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingTasksAttributeDo) Preload(fields ...field.RelationField) ILeasingTasksAttributeDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingTasksAttributeDo) FirstOrInit() (*model.LeasingTasksAttribute, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTasksAttribute), nil
	}
}

func (l leasingTasksAttributeDo) FirstOrCreate() (*model.LeasingTasksAttribute, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LeasingTasksAttribute), nil
	}
}

func (l leasingTasksAttributeDo) FindByPage(offset int, limit int) (result []*model.LeasingTasksAttribute, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingTasksAttributeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingTasksAttributeDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingTasksAttributeDo) Delete(models ...*model.LeasingTasksAttribute) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingTasksAttributeDo) withDO(do gen.Dao) *leasingTasksAttributeDo {
	l.DO = *do.(*gen.DO)
	return l
}
