// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newMotorAsset(db *gorm.DB, opts ...gen.DOOption) motorAsset {
	_motorAsset := motorAsset{}

	_motorAsset.motorAssetDo.UseDB(db, opts...)
	_motorAsset.motorAssetDo.UseModel(&model.MotorAsset{})

	tableName := _motorAsset.motorAssetDo.TableName()
	_motorAsset.ALL = field.NewAsterisk(tableName)
	_motorAsset.MoasID = field.NewInt64(tableName, "moas_id")
	_motorAsset.FileName = field.NewString(tableName, "file_name")
	_motorAsset.FileSize = field.NewFloat64(tableName, "file_size")
	_motorAsset.FileType = field.NewString(tableName, "file_type")
	_motorAsset.FileURL = field.NewString(tableName, "file_url")
	_motorAsset.MoasMotorID = field.NewInt64(tableName, "moas_motor_id")
	_motorAsset.CreatedAt = field.NewTime(tableName, "created_at")

	_motorAsset.fillFieldMap()

	return _motorAsset
}

type motorAsset struct {
	motorAssetDo

	ALL         field.Asterisk
	MoasID      field.Int64
	FileName    field.String
	FileSize    field.Float64
	FileType    field.String
	FileURL     field.String
	MoasMotorID field.Int64
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m motorAsset) Table(newTableName string) *motorAsset {
	m.motorAssetDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m motorAsset) As(alias string) *motorAsset {
	m.motorAssetDo.DO = *(m.motorAssetDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *motorAsset) updateTableName(table string) *motorAsset {
	m.ALL = field.NewAsterisk(table)
	m.MoasID = field.NewInt64(table, "moas_id")
	m.FileName = field.NewString(table, "file_name")
	m.FileSize = field.NewFloat64(table, "file_size")
	m.FileType = field.NewString(table, "file_type")
	m.FileURL = field.NewString(table, "file_url")
	m.MoasMotorID = field.NewInt64(table, "moas_motor_id")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *motorAsset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *motorAsset) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 7)
	m.fieldMap["moas_id"] = m.MoasID
	m.fieldMap["file_name"] = m.FileName
	m.fieldMap["file_size"] = m.FileSize
	m.fieldMap["file_type"] = m.FileType
	m.fieldMap["file_url"] = m.FileURL
	m.fieldMap["moas_motor_id"] = m.MoasMotorID
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m motorAsset) clone(db *gorm.DB) motorAsset {
	m.motorAssetDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m motorAsset) replaceDB(db *gorm.DB) motorAsset {
	m.motorAssetDo.ReplaceDB(db)
	return m
}

type motorAssetDo struct{ gen.DO }

type IMotorAssetDo interface {
	gen.SubQuery
	Debug() IMotorAssetDo
	WithContext(ctx context.Context) IMotorAssetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMotorAssetDo
	WriteDB() IMotorAssetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMotorAssetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMotorAssetDo
	Not(conds ...gen.Condition) IMotorAssetDo
	Or(conds ...gen.Condition) IMotorAssetDo
	Select(conds ...field.Expr) IMotorAssetDo
	Where(conds ...gen.Condition) IMotorAssetDo
	Order(conds ...field.Expr) IMotorAssetDo
	Distinct(cols ...field.Expr) IMotorAssetDo
	Omit(cols ...field.Expr) IMotorAssetDo
	Join(table schema.Tabler, on ...field.Expr) IMotorAssetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMotorAssetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMotorAssetDo
	Group(cols ...field.Expr) IMotorAssetDo
	Having(conds ...gen.Condition) IMotorAssetDo
	Limit(limit int) IMotorAssetDo
	Offset(offset int) IMotorAssetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMotorAssetDo
	Unscoped() IMotorAssetDo
	Create(values ...*model.MotorAsset) error
	CreateInBatches(values []*model.MotorAsset, batchSize int) error
	Save(values ...*model.MotorAsset) error
	First() (*model.MotorAsset, error)
	Take() (*model.MotorAsset, error)
	Last() (*model.MotorAsset, error)
	Find() ([]*model.MotorAsset, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MotorAsset, err error)
	FindInBatches(result *[]*model.MotorAsset, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MotorAsset) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMotorAssetDo
	Assign(attrs ...field.AssignExpr) IMotorAssetDo
	Joins(fields ...field.RelationField) IMotorAssetDo
	Preload(fields ...field.RelationField) IMotorAssetDo
	FirstOrInit() (*model.MotorAsset, error)
	FirstOrCreate() (*model.MotorAsset, error)
	FindByPage(offset int, limit int) (result []*model.MotorAsset, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMotorAssetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m motorAssetDo) Debug() IMotorAssetDo {
	return m.withDO(m.DO.Debug())
}

func (m motorAssetDo) WithContext(ctx context.Context) IMotorAssetDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m motorAssetDo) ReadDB() IMotorAssetDo {
	return m.Clauses(dbresolver.Read)
}

func (m motorAssetDo) WriteDB() IMotorAssetDo {
	return m.Clauses(dbresolver.Write)
}

func (m motorAssetDo) Session(config *gorm.Session) IMotorAssetDo {
	return m.withDO(m.DO.Session(config))
}

func (m motorAssetDo) Clauses(conds ...clause.Expression) IMotorAssetDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m motorAssetDo) Returning(value interface{}, columns ...string) IMotorAssetDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m motorAssetDo) Not(conds ...gen.Condition) IMotorAssetDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m motorAssetDo) Or(conds ...gen.Condition) IMotorAssetDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m motorAssetDo) Select(conds ...field.Expr) IMotorAssetDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m motorAssetDo) Where(conds ...gen.Condition) IMotorAssetDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m motorAssetDo) Order(conds ...field.Expr) IMotorAssetDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m motorAssetDo) Distinct(cols ...field.Expr) IMotorAssetDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m motorAssetDo) Omit(cols ...field.Expr) IMotorAssetDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m motorAssetDo) Join(table schema.Tabler, on ...field.Expr) IMotorAssetDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m motorAssetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMotorAssetDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m motorAssetDo) RightJoin(table schema.Tabler, on ...field.Expr) IMotorAssetDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m motorAssetDo) Group(cols ...field.Expr) IMotorAssetDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m motorAssetDo) Having(conds ...gen.Condition) IMotorAssetDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m motorAssetDo) Limit(limit int) IMotorAssetDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m motorAssetDo) Offset(offset int) IMotorAssetDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m motorAssetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMotorAssetDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m motorAssetDo) Unscoped() IMotorAssetDo {
	return m.withDO(m.DO.Unscoped())
}

func (m motorAssetDo) Create(values ...*model.MotorAsset) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m motorAssetDo) CreateInBatches(values []*model.MotorAsset, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m motorAssetDo) Save(values ...*model.MotorAsset) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m motorAssetDo) First() (*model.MotorAsset, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorAsset), nil
	}
}

func (m motorAssetDo) Take() (*model.MotorAsset, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorAsset), nil
	}
}

func (m motorAssetDo) Last() (*model.MotorAsset, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorAsset), nil
	}
}

func (m motorAssetDo) Find() ([]*model.MotorAsset, error) {
	result, err := m.DO.Find()
	return result.([]*model.MotorAsset), err
}

func (m motorAssetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MotorAsset, err error) {
	buf := make([]*model.MotorAsset, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m motorAssetDo) FindInBatches(result *[]*model.MotorAsset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m motorAssetDo) Attrs(attrs ...field.AssignExpr) IMotorAssetDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m motorAssetDo) Assign(attrs ...field.AssignExpr) IMotorAssetDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m motorAssetDo) Joins(fields ...field.RelationField) IMotorAssetDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m motorAssetDo) Preload(fields ...field.RelationField) IMotorAssetDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m motorAssetDo) FirstOrInit() (*model.MotorAsset, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorAsset), nil
	}
}

func (m motorAssetDo) FirstOrCreate() (*model.MotorAsset, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorAsset), nil
	}
}

func (m motorAssetDo) FindByPage(offset int, limit int) (result []*model.MotorAsset, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m motorAssetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m motorAssetDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m motorAssetDo) Delete(models ...*model.MotorAsset) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *motorAssetDo) withDO(do gen.Dao) *motorAssetDo {
	m.DO = *do.(*gen.DO)
	return m
}
