// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newMotor(db *gorm.DB, opts ...gen.DOOption) motor {
	_motor := motor{}

	_motor.motorDo.UseDB(db, opts...)
	_motor.motorDo.UseModel(&model.Motor{})

	tableName := _motor.motorDo.TableName()
	_motor.ALL = field.NewAsterisk(tableName)
	_motor.MotorID = field.NewInt64(tableName, "motor_id")
	_motor.Merk = field.NewString(tableName, "merk")
	_motor.MotorType = field.NewString(tableName, "motor_type")
	_motor.Tahun = field.NewInt16(tableName, "tahun")
	_motor.Warna = field.NewString(tableName, "warna")
	_motor.NomorRangka = field.NewString(tableName, "nomor_rangka")
	_motor.NomorMesin = field.NewString(tableName, "nomor_mesin")
	_motor.CcMesin = field.NewString(tableName, "cc_mesin")
	_motor.NomorPolisi = field.NewString(tableName, "nomor_polisi")
	_motor.StatusUnit = field.NewString(tableName, "status_unit")
	_motor.HargaOtr = field.NewFloat64(tableName, "harga_otr")
	_motor.MotorMotyID = field.NewInt64(tableName, "motor_moty_id")
	_motor.CreatedAt = field.NewTime(tableName, "created_at")

	_motor.fillFieldMap()

	return _motor
}

type motor struct {
	motorDo

	ALL         field.Asterisk
	MotorID     field.Int64
	Merk        field.String
	MotorType   field.String
	Tahun       field.Int16
	Warna       field.String
	NomorRangka field.String
	NomorMesin  field.String
	CcMesin     field.String
	NomorPolisi field.String
	StatusUnit  field.String
	HargaOtr    field.Float64
	MotorMotyID field.Int64
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m motor) Table(newTableName string) *motor {
	m.motorDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m motor) As(alias string) *motor {
	m.motorDo.DO = *(m.motorDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *motor) updateTableName(table string) *motor {
	m.ALL = field.NewAsterisk(table)
	m.MotorID = field.NewInt64(table, "motor_id")
	m.Merk = field.NewString(table, "merk")
	m.MotorType = field.NewString(table, "motor_type")
	m.Tahun = field.NewInt16(table, "tahun")
	m.Warna = field.NewString(table, "warna")
	m.NomorRangka = field.NewString(table, "nomor_rangka")
	m.NomorMesin = field.NewString(table, "nomor_mesin")
	m.CcMesin = field.NewString(table, "cc_mesin")
	m.NomorPolisi = field.NewString(table, "nomor_polisi")
	m.StatusUnit = field.NewString(table, "status_unit")
	m.HargaOtr = field.NewFloat64(table, "harga_otr")
	m.MotorMotyID = field.NewInt64(table, "motor_moty_id")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *motor) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *motor) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 13)
	m.fieldMap["motor_id"] = m.MotorID
	m.fieldMap["merk"] = m.Merk
	m.fieldMap["motor_type"] = m.MotorType
	m.fieldMap["tahun"] = m.Tahun
	m.fieldMap["warna"] = m.Warna
	m.fieldMap["nomor_rangka"] = m.NomorRangka
	m.fieldMap["nomor_mesin"] = m.NomorMesin
	m.fieldMap["cc_mesin"] = m.CcMesin
	m.fieldMap["nomor_polisi"] = m.NomorPolisi
	m.fieldMap["status_unit"] = m.StatusUnit
	m.fieldMap["harga_otr"] = m.HargaOtr
	m.fieldMap["motor_moty_id"] = m.MotorMotyID
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m motor) clone(db *gorm.DB) motor {
	m.motorDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m motor) replaceDB(db *gorm.DB) motor {
	m.motorDo.ReplaceDB(db)
	return m
}

type motorDo struct{ gen.DO }

type IMotorDo interface {
	gen.SubQuery
	Debug() IMotorDo
	WithContext(ctx context.Context) IMotorDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMotorDo
	WriteDB() IMotorDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMotorDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMotorDo
	Not(conds ...gen.Condition) IMotorDo
	Or(conds ...gen.Condition) IMotorDo
	Select(conds ...field.Expr) IMotorDo
	Where(conds ...gen.Condition) IMotorDo
	Order(conds ...field.Expr) IMotorDo
	Distinct(cols ...field.Expr) IMotorDo
	Omit(cols ...field.Expr) IMotorDo
	Join(table schema.Tabler, on ...field.Expr) IMotorDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMotorDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMotorDo
	Group(cols ...field.Expr) IMotorDo
	Having(conds ...gen.Condition) IMotorDo
	Limit(limit int) IMotorDo
	Offset(offset int) IMotorDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMotorDo
	Unscoped() IMotorDo
	Create(values ...*model.Motor) error
	CreateInBatches(values []*model.Motor, batchSize int) error
	Save(values ...*model.Motor) error
	First() (*model.Motor, error)
	Take() (*model.Motor, error)
	Last() (*model.Motor, error)
	Find() ([]*model.Motor, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Motor, err error)
	FindInBatches(result *[]*model.Motor, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Motor) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMotorDo
	Assign(attrs ...field.AssignExpr) IMotorDo
	Joins(fields ...field.RelationField) IMotorDo
	Preload(fields ...field.RelationField) IMotorDo
	FirstOrInit() (*model.Motor, error)
	FirstOrCreate() (*model.Motor, error)
	FindByPage(offset int, limit int) (result []*model.Motor, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMotorDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m motorDo) Debug() IMotorDo {
	return m.withDO(m.DO.Debug())
}

func (m motorDo) WithContext(ctx context.Context) IMotorDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m motorDo) ReadDB() IMotorDo {
	return m.Clauses(dbresolver.Read)
}

func (m motorDo) WriteDB() IMotorDo {
	return m.Clauses(dbresolver.Write)
}

func (m motorDo) Session(config *gorm.Session) IMotorDo {
	return m.withDO(m.DO.Session(config))
}

func (m motorDo) Clauses(conds ...clause.Expression) IMotorDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m motorDo) Returning(value interface{}, columns ...string) IMotorDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m motorDo) Not(conds ...gen.Condition) IMotorDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m motorDo) Or(conds ...gen.Condition) IMotorDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m motorDo) Select(conds ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m motorDo) Where(conds ...gen.Condition) IMotorDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m motorDo) Order(conds ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m motorDo) Distinct(cols ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m motorDo) Omit(cols ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m motorDo) Join(table schema.Tabler, on ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m motorDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMotorDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m motorDo) RightJoin(table schema.Tabler, on ...field.Expr) IMotorDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m motorDo) Group(cols ...field.Expr) IMotorDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m motorDo) Having(conds ...gen.Condition) IMotorDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m motorDo) Limit(limit int) IMotorDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m motorDo) Offset(offset int) IMotorDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m motorDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMotorDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m motorDo) Unscoped() IMotorDo {
	return m.withDO(m.DO.Unscoped())
}

func (m motorDo) Create(values ...*model.Motor) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m motorDo) CreateInBatches(values []*model.Motor, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m motorDo) Save(values ...*model.Motor) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m motorDo) First() (*model.Motor, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Motor), nil
	}
}

func (m motorDo) Take() (*model.Motor, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Motor), nil
	}
}

func (m motorDo) Last() (*model.Motor, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Motor), nil
	}
}

func (m motorDo) Find() ([]*model.Motor, error) {
	result, err := m.DO.Find()
	return result.([]*model.Motor), err
}

func (m motorDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Motor, err error) {
	buf := make([]*model.Motor, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m motorDo) FindInBatches(result *[]*model.Motor, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m motorDo) Attrs(attrs ...field.AssignExpr) IMotorDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m motorDo) Assign(attrs ...field.AssignExpr) IMotorDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m motorDo) Joins(fields ...field.RelationField) IMotorDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m motorDo) Preload(fields ...field.RelationField) IMotorDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m motorDo) FirstOrInit() (*model.Motor, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Motor), nil
	}
}

func (m motorDo) FirstOrCreate() (*model.Motor, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Motor), nil
	}
}

func (m motorDo) FindByPage(offset int, limit int) (result []*model.Motor, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m motorDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m motorDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m motorDo) Delete(models ...*model.Motor) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *motorDo) withDO(do gen.Dao) *motorDo {
	m.DO = *do.(*gen.DO)
	return m
}
