// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newMotorType(db *gorm.DB, opts ...gen.DOOption) motorType {
	_motorType := motorType{}

	_motorType.motorTypeDo.UseDB(db, opts...)
	_motorType.motorTypeDo.UseModel(&model.MotorType{})

	tableName := _motorType.motorTypeDo.TableName()
	_motorType.ALL = field.NewAsterisk(tableName)
	_motorType.MotyID = field.NewInt64(tableName, "moty_id")
	_motorType.MotyName = field.NewString(tableName, "moty_name")

	_motorType.fillFieldMap()

	return _motorType
}

type motorType struct {
	motorTypeDo

	ALL      field.Asterisk
	MotyID   field.Int64
	MotyName field.String

	fieldMap map[string]field.Expr
}

func (m motorType) Table(newTableName string) *motorType {
	m.motorTypeDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m motorType) As(alias string) *motorType {
	m.motorTypeDo.DO = *(m.motorTypeDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *motorType) updateTableName(table string) *motorType {
	m.ALL = field.NewAsterisk(table)
	m.MotyID = field.NewInt64(table, "moty_id")
	m.MotyName = field.NewString(table, "moty_name")

	m.fillFieldMap()

	return m
}

func (m *motorType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *motorType) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 2)
	m.fieldMap["moty_id"] = m.MotyID
	m.fieldMap["moty_name"] = m.MotyName
}

func (m motorType) clone(db *gorm.DB) motorType {
	m.motorTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m motorType) replaceDB(db *gorm.DB) motorType {
	m.motorTypeDo.ReplaceDB(db)
	return m
}

type motorTypeDo struct{ gen.DO }

type IMotorTypeDo interface {
	gen.SubQuery
	Debug() IMotorTypeDo
	WithContext(ctx context.Context) IMotorTypeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMotorTypeDo
	WriteDB() IMotorTypeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMotorTypeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMotorTypeDo
	Not(conds ...gen.Condition) IMotorTypeDo
	Or(conds ...gen.Condition) IMotorTypeDo
	Select(conds ...field.Expr) IMotorTypeDo
	Where(conds ...gen.Condition) IMotorTypeDo
	Order(conds ...field.Expr) IMotorTypeDo
	Distinct(cols ...field.Expr) IMotorTypeDo
	Omit(cols ...field.Expr) IMotorTypeDo
	Join(table schema.Tabler, on ...field.Expr) IMotorTypeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMotorTypeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMotorTypeDo
	Group(cols ...field.Expr) IMotorTypeDo
	Having(conds ...gen.Condition) IMotorTypeDo
	Limit(limit int) IMotorTypeDo
	Offset(offset int) IMotorTypeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMotorTypeDo
	Unscoped() IMotorTypeDo
	Create(values ...*model.MotorType) error
	CreateInBatches(values []*model.MotorType, batchSize int) error
	Save(values ...*model.MotorType) error
	First() (*model.MotorType, error)
	Take() (*model.MotorType, error)
	Last() (*model.MotorType, error)
	Find() ([]*model.MotorType, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MotorType, err error)
	FindInBatches(result *[]*model.MotorType, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MotorType) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMotorTypeDo
	Assign(attrs ...field.AssignExpr) IMotorTypeDo
	Joins(fields ...field.RelationField) IMotorTypeDo
	Preload(fields ...field.RelationField) IMotorTypeDo
	FirstOrInit() (*model.MotorType, error)
	FirstOrCreate() (*model.MotorType, error)
	FindByPage(offset int, limit int) (result []*model.MotorType, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMotorTypeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m motorTypeDo) Debug() IMotorTypeDo {
	return m.withDO(m.DO.Debug())
}

func (m motorTypeDo) WithContext(ctx context.Context) IMotorTypeDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m motorTypeDo) ReadDB() IMotorTypeDo {
	return m.Clauses(dbresolver.Read)
}

func (m motorTypeDo) WriteDB() IMotorTypeDo {
	return m.Clauses(dbresolver.Write)
}

func (m motorTypeDo) Session(config *gorm.Session) IMotorTypeDo {
	return m.withDO(m.DO.Session(config))
}

func (m motorTypeDo) Clauses(conds ...clause.Expression) IMotorTypeDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m motorTypeDo) Returning(value interface{}, columns ...string) IMotorTypeDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m motorTypeDo) Not(conds ...gen.Condition) IMotorTypeDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m motorTypeDo) Or(conds ...gen.Condition) IMotorTypeDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m motorTypeDo) Select(conds ...field.Expr) IMotorTypeDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m motorTypeDo) Where(conds ...gen.Condition) IMotorTypeDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m motorTypeDo) Order(conds ...field.Expr) IMotorTypeDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m motorTypeDo) Distinct(cols ...field.Expr) IMotorTypeDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m motorTypeDo) Omit(cols ...field.Expr) IMotorTypeDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m motorTypeDo) Join(table schema.Tabler, on ...field.Expr) IMotorTypeDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m motorTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMotorTypeDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m motorTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) IMotorTypeDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m motorTypeDo) Group(cols ...field.Expr) IMotorTypeDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m motorTypeDo) Having(conds ...gen.Condition) IMotorTypeDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m motorTypeDo) Limit(limit int) IMotorTypeDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m motorTypeDo) Offset(offset int) IMotorTypeDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m motorTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMotorTypeDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m motorTypeDo) Unscoped() IMotorTypeDo {
	return m.withDO(m.DO.Unscoped())
}

func (m motorTypeDo) Create(values ...*model.MotorType) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m motorTypeDo) CreateInBatches(values []*model.MotorType, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m motorTypeDo) Save(values ...*model.MotorType) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m motorTypeDo) First() (*model.MotorType, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorType), nil
	}
}

func (m motorTypeDo) Take() (*model.MotorType, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorType), nil
	}
}

func (m motorTypeDo) Last() (*model.MotorType, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorType), nil
	}
}

func (m motorTypeDo) Find() ([]*model.MotorType, error) {
	result, err := m.DO.Find()
	return result.([]*model.MotorType), err
}

func (m motorTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MotorType, err error) {
	buf := make([]*model.MotorType, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m motorTypeDo) FindInBatches(result *[]*model.MotorType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m motorTypeDo) Attrs(attrs ...field.AssignExpr) IMotorTypeDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m motorTypeDo) Assign(attrs ...field.AssignExpr) IMotorTypeDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m motorTypeDo) Joins(fields ...field.RelationField) IMotorTypeDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m motorTypeDo) Preload(fields ...field.RelationField) IMotorTypeDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m motorTypeDo) FirstOrInit() (*model.MotorType, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorType), nil
	}
}

func (m motorTypeDo) FirstOrCreate() (*model.MotorType, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MotorType), nil
	}
}

func (m motorTypeDo) FindByPage(offset int, limit int) (result []*model.MotorType, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m motorTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m motorTypeDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m motorTypeDo) Delete(models ...*model.MotorType) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *motorTypeDo) withDO(do gen.Dao) *motorTypeDo {
	m.DO = *do.(*gen.DO)
	return m
}
