// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newOauthProvider(db *gorm.DB, opts ...gen.DOOption) oauthProvider {
	_oauthProvider := oauthProvider{}

	_oauthProvider.oauthProviderDo.UseDB(db, opts...)
	_oauthProvider.oauthProviderDo.UseModel(&model.OauthProvider{})

	tableName := _oauthProvider.oauthProviderDo.TableName()
	_oauthProvider.ALL = field.NewAsterisk(tableName)
	_oauthProvider.ProviderID = field.NewInt64(tableName, "provider_id")
	_oauthProvider.ProviderName = field.NewString(tableName, "provider_name")
	_oauthProvider.ClientID = field.NewString(tableName, "client_id")
	_oauthProvider.ClientSecret = field.NewString(tableName, "client_secret")
	_oauthProvider.RedirectURI = field.NewString(tableName, "redirect_uri")
	_oauthProvider.IssuerURL = field.NewString(tableName, "issuer_url")
	_oauthProvider.Active = field.NewBool(tableName, "active")
	_oauthProvider.CreatedAt = field.NewTime(tableName, "created_at")
	_oauthProvider.UpdatedAt = field.NewTime(tableName, "updated_at")

	_oauthProvider.fillFieldMap()

	return _oauthProvider
}

type oauthProvider struct {
	oauthProviderDo

	ALL          field.Asterisk
	ProviderID   field.Int64
	ProviderName field.String
	ClientID     field.String
	ClientSecret field.String
	RedirectURI  field.String
	IssuerURL    field.String
	Active       field.Bool
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (o oauthProvider) Table(newTableName string) *oauthProvider {
	o.oauthProviderDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oauthProvider) As(alias string) *oauthProvider {
	o.oauthProviderDo.DO = *(o.oauthProviderDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oauthProvider) updateTableName(table string) *oauthProvider {
	o.ALL = field.NewAsterisk(table)
	o.ProviderID = field.NewInt64(table, "provider_id")
	o.ProviderName = field.NewString(table, "provider_name")
	o.ClientID = field.NewString(table, "client_id")
	o.ClientSecret = field.NewString(table, "client_secret")
	o.RedirectURI = field.NewString(table, "redirect_uri")
	o.IssuerURL = field.NewString(table, "issuer_url")
	o.Active = field.NewBool(table, "active")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *oauthProvider) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oauthProvider) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 9)
	o.fieldMap["provider_id"] = o.ProviderID
	o.fieldMap["provider_name"] = o.ProviderName
	o.fieldMap["client_id"] = o.ClientID
	o.fieldMap["client_secret"] = o.ClientSecret
	o.fieldMap["redirect_uri"] = o.RedirectURI
	o.fieldMap["issuer_url"] = o.IssuerURL
	o.fieldMap["active"] = o.Active
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o oauthProvider) clone(db *gorm.DB) oauthProvider {
	o.oauthProviderDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o oauthProvider) replaceDB(db *gorm.DB) oauthProvider {
	o.oauthProviderDo.ReplaceDB(db)
	return o
}

type oauthProviderDo struct{ gen.DO }

type IOauthProviderDo interface {
	gen.SubQuery
	Debug() IOauthProviderDo
	WithContext(ctx context.Context) IOauthProviderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOauthProviderDo
	WriteDB() IOauthProviderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOauthProviderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOauthProviderDo
	Not(conds ...gen.Condition) IOauthProviderDo
	Or(conds ...gen.Condition) IOauthProviderDo
	Select(conds ...field.Expr) IOauthProviderDo
	Where(conds ...gen.Condition) IOauthProviderDo
	Order(conds ...field.Expr) IOauthProviderDo
	Distinct(cols ...field.Expr) IOauthProviderDo
	Omit(cols ...field.Expr) IOauthProviderDo
	Join(table schema.Tabler, on ...field.Expr) IOauthProviderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOauthProviderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOauthProviderDo
	Group(cols ...field.Expr) IOauthProviderDo
	Having(conds ...gen.Condition) IOauthProviderDo
	Limit(limit int) IOauthProviderDo
	Offset(offset int) IOauthProviderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOauthProviderDo
	Unscoped() IOauthProviderDo
	Create(values ...*model.OauthProvider) error
	CreateInBatches(values []*model.OauthProvider, batchSize int) error
	Save(values ...*model.OauthProvider) error
	First() (*model.OauthProvider, error)
	Take() (*model.OauthProvider, error)
	Last() (*model.OauthProvider, error)
	Find() ([]*model.OauthProvider, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OauthProvider, err error)
	FindInBatches(result *[]*model.OauthProvider, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OauthProvider) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOauthProviderDo
	Assign(attrs ...field.AssignExpr) IOauthProviderDo
	Joins(fields ...field.RelationField) IOauthProviderDo
	Preload(fields ...field.RelationField) IOauthProviderDo
	FirstOrInit() (*model.OauthProvider, error)
	FirstOrCreate() (*model.OauthProvider, error)
	FindByPage(offset int, limit int) (result []*model.OauthProvider, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOauthProviderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o oauthProviderDo) Debug() IOauthProviderDo {
	return o.withDO(o.DO.Debug())
}

func (o oauthProviderDo) WithContext(ctx context.Context) IOauthProviderDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oauthProviderDo) ReadDB() IOauthProviderDo {
	return o.Clauses(dbresolver.Read)
}

func (o oauthProviderDo) WriteDB() IOauthProviderDo {
	return o.Clauses(dbresolver.Write)
}

func (o oauthProviderDo) Session(config *gorm.Session) IOauthProviderDo {
	return o.withDO(o.DO.Session(config))
}

func (o oauthProviderDo) Clauses(conds ...clause.Expression) IOauthProviderDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oauthProviderDo) Returning(value interface{}, columns ...string) IOauthProviderDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oauthProviderDo) Not(conds ...gen.Condition) IOauthProviderDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oauthProviderDo) Or(conds ...gen.Condition) IOauthProviderDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oauthProviderDo) Select(conds ...field.Expr) IOauthProviderDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oauthProviderDo) Where(conds ...gen.Condition) IOauthProviderDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oauthProviderDo) Order(conds ...field.Expr) IOauthProviderDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oauthProviderDo) Distinct(cols ...field.Expr) IOauthProviderDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oauthProviderDo) Omit(cols ...field.Expr) IOauthProviderDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oauthProviderDo) Join(table schema.Tabler, on ...field.Expr) IOauthProviderDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oauthProviderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOauthProviderDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oauthProviderDo) RightJoin(table schema.Tabler, on ...field.Expr) IOauthProviderDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oauthProviderDo) Group(cols ...field.Expr) IOauthProviderDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oauthProviderDo) Having(conds ...gen.Condition) IOauthProviderDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oauthProviderDo) Limit(limit int) IOauthProviderDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oauthProviderDo) Offset(offset int) IOauthProviderDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oauthProviderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOauthProviderDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oauthProviderDo) Unscoped() IOauthProviderDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oauthProviderDo) Create(values ...*model.OauthProvider) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oauthProviderDo) CreateInBatches(values []*model.OauthProvider, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oauthProviderDo) Save(values ...*model.OauthProvider) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oauthProviderDo) First() (*model.OauthProvider, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthProvider), nil
	}
}

func (o oauthProviderDo) Take() (*model.OauthProvider, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthProvider), nil
	}
}

func (o oauthProviderDo) Last() (*model.OauthProvider, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthProvider), nil
	}
}

func (o oauthProviderDo) Find() ([]*model.OauthProvider, error) {
	result, err := o.DO.Find()
	return result.([]*model.OauthProvider), err
}

func (o oauthProviderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OauthProvider, err error) {
	buf := make([]*model.OauthProvider, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oauthProviderDo) FindInBatches(result *[]*model.OauthProvider, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oauthProviderDo) Attrs(attrs ...field.AssignExpr) IOauthProviderDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oauthProviderDo) Assign(attrs ...field.AssignExpr) IOauthProviderDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oauthProviderDo) Joins(fields ...field.RelationField) IOauthProviderDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oauthProviderDo) Preload(fields ...field.RelationField) IOauthProviderDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oauthProviderDo) FirstOrInit() (*model.OauthProvider, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthProvider), nil
	}
}

func (o oauthProviderDo) FirstOrCreate() (*model.OauthProvider, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthProvider), nil
	}
}

func (o oauthProviderDo) FindByPage(offset int, limit int) (result []*model.OauthProvider, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oauthProviderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oauthProviderDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oauthProviderDo) Delete(models ...*model.OauthProvider) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oauthProviderDo) withDO(do gen.Dao) *oauthProviderDo {
	o.DO = *do.(*gen.DO)
	return o
}
