// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newPaymentSchedule(db *gorm.DB, opts ...gen.DOOption) paymentSchedule {
	_paymentSchedule := paymentSchedule{}

	_paymentSchedule.paymentScheduleDo.UseDB(db, opts...)
	_paymentSchedule.paymentScheduleDo.UseModel(&model.PaymentSchedule{})

	tableName := _paymentSchedule.paymentScheduleDo.TableName()
	_paymentSchedule.ALL = field.NewAsterisk(tableName)
	_paymentSchedule.ScheduleID = field.NewInt64(tableName, "schedule_id")
	_paymentSchedule.AngsuranKe = field.NewInt16(tableName, "angsuran_ke")
	_paymentSchedule.JatuhTempo = field.NewTime(tableName, "jatuh_tempo")
	_paymentSchedule.Pokok = field.NewFloat64(tableName, "pokok")
	_paymentSchedule.Margin = field.NewFloat64(tableName, "margin")
	_paymentSchedule.TotalTagihan = field.NewFloat64(tableName, "total_tagihan")
	_paymentSchedule.StatusPembayaran = field.NewString(tableName, "status_pembayaran")
	_paymentSchedule.TanggalBayar = field.NewTime(tableName, "tanggal_bayar")
	_paymentSchedule.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentSchedule.ContractID = field.NewInt64(tableName, "contract_id")

	_paymentSchedule.fillFieldMap()

	return _paymentSchedule
}

type paymentSchedule struct {
	paymentScheduleDo

	ALL              field.Asterisk
	ScheduleID       field.Int64
	AngsuranKe       field.Int16
	JatuhTempo       field.Time
	Pokok            field.Float64
	Margin           field.Float64
	TotalTagihan     field.Float64
	StatusPembayaran field.String
	TanggalBayar     field.Time
	CreatedAt        field.Time
	ContractID       field.Int64

	fieldMap map[string]field.Expr
}

func (p paymentSchedule) Table(newTableName string) *paymentSchedule {
	p.paymentScheduleDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentSchedule) As(alias string) *paymentSchedule {
	p.paymentScheduleDo.DO = *(p.paymentScheduleDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentSchedule) updateTableName(table string) *paymentSchedule {
	p.ALL = field.NewAsterisk(table)
	p.ScheduleID = field.NewInt64(table, "schedule_id")
	p.AngsuranKe = field.NewInt16(table, "angsuran_ke")
	p.JatuhTempo = field.NewTime(table, "jatuh_tempo")
	p.Pokok = field.NewFloat64(table, "pokok")
	p.Margin = field.NewFloat64(table, "margin")
	p.TotalTagihan = field.NewFloat64(table, "total_tagihan")
	p.StatusPembayaran = field.NewString(table, "status_pembayaran")
	p.TanggalBayar = field.NewTime(table, "tanggal_bayar")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.ContractID = field.NewInt64(table, "contract_id")

	p.fillFieldMap()

	return p
}

func (p *paymentSchedule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentSchedule) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["schedule_id"] = p.ScheduleID
	p.fieldMap["angsuran_ke"] = p.AngsuranKe
	p.fieldMap["jatuh_tempo"] = p.JatuhTempo
	p.fieldMap["pokok"] = p.Pokok
	p.fieldMap["margin"] = p.Margin
	p.fieldMap["total_tagihan"] = p.TotalTagihan
	p.fieldMap["status_pembayaran"] = p.StatusPembayaran
	p.fieldMap["tanggal_bayar"] = p.TanggalBayar
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["contract_id"] = p.ContractID
}

func (p paymentSchedule) clone(db *gorm.DB) paymentSchedule {
	p.paymentScheduleDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentSchedule) replaceDB(db *gorm.DB) paymentSchedule {
	p.paymentScheduleDo.ReplaceDB(db)
	return p
}

type paymentScheduleDo struct{ gen.DO }

type IPaymentScheduleDo interface {
	gen.SubQuery
	Debug() IPaymentScheduleDo
	WithContext(ctx context.Context) IPaymentScheduleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentScheduleDo
	WriteDB() IPaymentScheduleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentScheduleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentScheduleDo
	Not(conds ...gen.Condition) IPaymentScheduleDo
	Or(conds ...gen.Condition) IPaymentScheduleDo
	Select(conds ...field.Expr) IPaymentScheduleDo
	Where(conds ...gen.Condition) IPaymentScheduleDo
	Order(conds ...field.Expr) IPaymentScheduleDo
	Distinct(cols ...field.Expr) IPaymentScheduleDo
	Omit(cols ...field.Expr) IPaymentScheduleDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo
	Group(cols ...field.Expr) IPaymentScheduleDo
	Having(conds ...gen.Condition) IPaymentScheduleDo
	Limit(limit int) IPaymentScheduleDo
	Offset(offset int) IPaymentScheduleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentScheduleDo
	Unscoped() IPaymentScheduleDo
	Create(values ...*model.PaymentSchedule) error
	CreateInBatches(values []*model.PaymentSchedule, batchSize int) error
	Save(values ...*model.PaymentSchedule) error
	First() (*model.PaymentSchedule, error)
	Take() (*model.PaymentSchedule, error)
	Last() (*model.PaymentSchedule, error)
	Find() ([]*model.PaymentSchedule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentSchedule, err error)
	FindInBatches(result *[]*model.PaymentSchedule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PaymentSchedule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentScheduleDo
	Assign(attrs ...field.AssignExpr) IPaymentScheduleDo
	Joins(fields ...field.RelationField) IPaymentScheduleDo
	Preload(fields ...field.RelationField) IPaymentScheduleDo
	FirstOrInit() (*model.PaymentSchedule, error)
	FirstOrCreate() (*model.PaymentSchedule, error)
	FindByPage(offset int, limit int) (result []*model.PaymentSchedule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentScheduleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentScheduleDo) Debug() IPaymentScheduleDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentScheduleDo) WithContext(ctx context.Context) IPaymentScheduleDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentScheduleDo) ReadDB() IPaymentScheduleDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentScheduleDo) WriteDB() IPaymentScheduleDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentScheduleDo) Session(config *gorm.Session) IPaymentScheduleDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentScheduleDo) Clauses(conds ...clause.Expression) IPaymentScheduleDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentScheduleDo) Returning(value interface{}, columns ...string) IPaymentScheduleDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentScheduleDo) Not(conds ...gen.Condition) IPaymentScheduleDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentScheduleDo) Or(conds ...gen.Condition) IPaymentScheduleDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentScheduleDo) Select(conds ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentScheduleDo) Where(conds ...gen.Condition) IPaymentScheduleDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentScheduleDo) Order(conds ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentScheduleDo) Distinct(cols ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentScheduleDo) Omit(cols ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentScheduleDo) Join(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentScheduleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentScheduleDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentScheduleDo) Group(cols ...field.Expr) IPaymentScheduleDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentScheduleDo) Having(conds ...gen.Condition) IPaymentScheduleDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentScheduleDo) Limit(limit int) IPaymentScheduleDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentScheduleDo) Offset(offset int) IPaymentScheduleDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentScheduleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentScheduleDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentScheduleDo) Unscoped() IPaymentScheduleDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentScheduleDo) Create(values ...*model.PaymentSchedule) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentScheduleDo) CreateInBatches(values []*model.PaymentSchedule, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentScheduleDo) Save(values ...*model.PaymentSchedule) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentScheduleDo) First() (*model.PaymentSchedule, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) Take() (*model.PaymentSchedule, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) Last() (*model.PaymentSchedule, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) Find() ([]*model.PaymentSchedule, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentSchedule), err
}

func (p paymentScheduleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentSchedule, err error) {
	buf := make([]*model.PaymentSchedule, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentScheduleDo) FindInBatches(result *[]*model.PaymentSchedule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentScheduleDo) Attrs(attrs ...field.AssignExpr) IPaymentScheduleDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentScheduleDo) Assign(attrs ...field.AssignExpr) IPaymentScheduleDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentScheduleDo) Joins(fields ...field.RelationField) IPaymentScheduleDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentScheduleDo) Preload(fields ...field.RelationField) IPaymentScheduleDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentScheduleDo) FirstOrInit() (*model.PaymentSchedule, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) FirstOrCreate() (*model.PaymentSchedule, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentSchedule), nil
	}
}

func (p paymentScheduleDo) FindByPage(offset int, limit int) (result []*model.PaymentSchedule, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentScheduleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentScheduleDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentScheduleDo) Delete(models ...*model.PaymentSchedule) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentScheduleDo) withDO(do gen.Dao) *paymentScheduleDo {
	p.DO = *do.(*gen.DO)
	return p
}
