// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newTemplateTaskAttribute(db *gorm.DB, opts ...gen.DOOption) templateTaskAttribute {
	_templateTaskAttribute := templateTaskAttribute{}

	_templateTaskAttribute.templateTaskAttributeDo.UseDB(db, opts...)
	_templateTaskAttribute.templateTaskAttributeDo.UseModel(&model.TemplateTaskAttribute{})

	tableName := _templateTaskAttribute.templateTaskAttributeDo.TableName()
	_templateTaskAttribute.ALL = field.NewAsterisk(tableName)
	_templateTaskAttribute.TetatID = field.NewInt64(tableName, "tetat_id")
	_templateTaskAttribute.TetatName = field.NewString(tableName, "tetat_name")
	_templateTaskAttribute.TetatTetaID = field.NewInt64(tableName, "tetat_teta_id")
	_templateTaskAttribute.Description = field.NewString(tableName, "description")
	_templateTaskAttribute.IsRequired = field.NewBool(tableName, "is_required")
	_templateTaskAttribute.AttributeType = field.NewString(tableName, "attribute_type")
	_templateTaskAttribute.CreatedAt = field.NewTime(tableName, "created_at")

	_templateTaskAttribute.fillFieldMap()

	return _templateTaskAttribute
}

type templateTaskAttribute struct {
	templateTaskAttributeDo

	ALL           field.Asterisk
	TetatID       field.Int64
	TetatName     field.String
	TetatTetaID   field.Int64
	Description   field.String
	IsRequired    field.Bool
	AttributeType field.String
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (t templateTaskAttribute) Table(newTableName string) *templateTaskAttribute {
	t.templateTaskAttributeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t templateTaskAttribute) As(alias string) *templateTaskAttribute {
	t.templateTaskAttributeDo.DO = *(t.templateTaskAttributeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *templateTaskAttribute) updateTableName(table string) *templateTaskAttribute {
	t.ALL = field.NewAsterisk(table)
	t.TetatID = field.NewInt64(table, "tetat_id")
	t.TetatName = field.NewString(table, "tetat_name")
	t.TetatTetaID = field.NewInt64(table, "tetat_teta_id")
	t.Description = field.NewString(table, "description")
	t.IsRequired = field.NewBool(table, "is_required")
	t.AttributeType = field.NewString(table, "attribute_type")
	t.CreatedAt = field.NewTime(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *templateTaskAttribute) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *templateTaskAttribute) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["tetat_id"] = t.TetatID
	t.fieldMap["tetat_name"] = t.TetatName
	t.fieldMap["tetat_teta_id"] = t.TetatTetaID
	t.fieldMap["description"] = t.Description
	t.fieldMap["is_required"] = t.IsRequired
	t.fieldMap["attribute_type"] = t.AttributeType
	t.fieldMap["created_at"] = t.CreatedAt
}

func (t templateTaskAttribute) clone(db *gorm.DB) templateTaskAttribute {
	t.templateTaskAttributeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t templateTaskAttribute) replaceDB(db *gorm.DB) templateTaskAttribute {
	t.templateTaskAttributeDo.ReplaceDB(db)
	return t
}

type templateTaskAttributeDo struct{ gen.DO }

type ITemplateTaskAttributeDo interface {
	gen.SubQuery
	Debug() ITemplateTaskAttributeDo
	WithContext(ctx context.Context) ITemplateTaskAttributeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITemplateTaskAttributeDo
	WriteDB() ITemplateTaskAttributeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITemplateTaskAttributeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITemplateTaskAttributeDo
	Not(conds ...gen.Condition) ITemplateTaskAttributeDo
	Or(conds ...gen.Condition) ITemplateTaskAttributeDo
	Select(conds ...field.Expr) ITemplateTaskAttributeDo
	Where(conds ...gen.Condition) ITemplateTaskAttributeDo
	Order(conds ...field.Expr) ITemplateTaskAttributeDo
	Distinct(cols ...field.Expr) ITemplateTaskAttributeDo
	Omit(cols ...field.Expr) ITemplateTaskAttributeDo
	Join(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo
	Group(cols ...field.Expr) ITemplateTaskAttributeDo
	Having(conds ...gen.Condition) ITemplateTaskAttributeDo
	Limit(limit int) ITemplateTaskAttributeDo
	Offset(offset int) ITemplateTaskAttributeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITemplateTaskAttributeDo
	Unscoped() ITemplateTaskAttributeDo
	Create(values ...*model.TemplateTaskAttribute) error
	CreateInBatches(values []*model.TemplateTaskAttribute, batchSize int) error
	Save(values ...*model.TemplateTaskAttribute) error
	First() (*model.TemplateTaskAttribute, error)
	Take() (*model.TemplateTaskAttribute, error)
	Last() (*model.TemplateTaskAttribute, error)
	Find() ([]*model.TemplateTaskAttribute, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TemplateTaskAttribute, err error)
	FindInBatches(result *[]*model.TemplateTaskAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TemplateTaskAttribute) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITemplateTaskAttributeDo
	Assign(attrs ...field.AssignExpr) ITemplateTaskAttributeDo
	Joins(fields ...field.RelationField) ITemplateTaskAttributeDo
	Preload(fields ...field.RelationField) ITemplateTaskAttributeDo
	FirstOrInit() (*model.TemplateTaskAttribute, error)
	FirstOrCreate() (*model.TemplateTaskAttribute, error)
	FindByPage(offset int, limit int) (result []*model.TemplateTaskAttribute, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITemplateTaskAttributeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t templateTaskAttributeDo) Debug() ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Debug())
}

func (t templateTaskAttributeDo) WithContext(ctx context.Context) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t templateTaskAttributeDo) ReadDB() ITemplateTaskAttributeDo {
	return t.Clauses(dbresolver.Read)
}

func (t templateTaskAttributeDo) WriteDB() ITemplateTaskAttributeDo {
	return t.Clauses(dbresolver.Write)
}

func (t templateTaskAttributeDo) Session(config *gorm.Session) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Session(config))
}

func (t templateTaskAttributeDo) Clauses(conds ...clause.Expression) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t templateTaskAttributeDo) Returning(value interface{}, columns ...string) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t templateTaskAttributeDo) Not(conds ...gen.Condition) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t templateTaskAttributeDo) Or(conds ...gen.Condition) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t templateTaskAttributeDo) Select(conds ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t templateTaskAttributeDo) Where(conds ...gen.Condition) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t templateTaskAttributeDo) Order(conds ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t templateTaskAttributeDo) Distinct(cols ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t templateTaskAttributeDo) Omit(cols ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t templateTaskAttributeDo) Join(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t templateTaskAttributeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t templateTaskAttributeDo) RightJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t templateTaskAttributeDo) Group(cols ...field.Expr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t templateTaskAttributeDo) Having(conds ...gen.Condition) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t templateTaskAttributeDo) Limit(limit int) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t templateTaskAttributeDo) Offset(offset int) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t templateTaskAttributeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t templateTaskAttributeDo) Unscoped() ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t templateTaskAttributeDo) Create(values ...*model.TemplateTaskAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t templateTaskAttributeDo) CreateInBatches(values []*model.TemplateTaskAttribute, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t templateTaskAttributeDo) Save(values ...*model.TemplateTaskAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t templateTaskAttributeDo) First() (*model.TemplateTaskAttribute, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) Take() (*model.TemplateTaskAttribute, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) Last() (*model.TemplateTaskAttribute, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) Find() ([]*model.TemplateTaskAttribute, error) {
	result, err := t.DO.Find()
	return result.([]*model.TemplateTaskAttribute), err
}

func (t templateTaskAttributeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TemplateTaskAttribute, err error) {
	buf := make([]*model.TemplateTaskAttribute, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t templateTaskAttributeDo) FindInBatches(result *[]*model.TemplateTaskAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t templateTaskAttributeDo) Attrs(attrs ...field.AssignExpr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t templateTaskAttributeDo) Assign(attrs ...field.AssignExpr) ITemplateTaskAttributeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t templateTaskAttributeDo) Joins(fields ...field.RelationField) ITemplateTaskAttributeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t templateTaskAttributeDo) Preload(fields ...field.RelationField) ITemplateTaskAttributeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t templateTaskAttributeDo) FirstOrInit() (*model.TemplateTaskAttribute, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) FirstOrCreate() (*model.TemplateTaskAttribute, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTaskAttribute), nil
	}
}

func (t templateTaskAttributeDo) FindByPage(offset int, limit int) (result []*model.TemplateTaskAttribute, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t templateTaskAttributeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t templateTaskAttributeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t templateTaskAttributeDo) Delete(models ...*model.TemplateTaskAttribute) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *templateTaskAttributeDo) withDO(do gen.Dao) *templateTaskAttributeDo {
	t.DO = *do.(*gen.DO)
	return t
}
