// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"honda-leasing-api/internal/domain/model"
)

func newTemplateTask(db *gorm.DB, opts ...gen.DOOption) templateTask {
	_templateTask := templateTask{}

	_templateTask.templateTaskDo.UseDB(db, opts...)
	_templateTask.templateTaskDo.UseModel(&model.TemplateTask{})

	tableName := _templateTask.templateTaskDo.TableName()
	_templateTask.ALL = field.NewAsterisk(tableName)
	_templateTask.TetaID = field.NewInt64(tableName, "teta_id")
	_templateTask.TetaName = field.NewString(tableName, "teta_name")
	_templateTask.TetaRoleID = field.NewInt64(tableName, "teta_role_id")
	_templateTask.Description = field.NewString(tableName, "description")
	_templateTask.SequenceNo = field.NewInt16(tableName, "sequence_no")
	_templateTask.IsRequired = field.NewBool(tableName, "is_required")
	_templateTask.CreatedAt = field.NewTime(tableName, "created_at")
	_templateTask.UpdatedAt = field.NewTime(tableName, "updated_at")
	_templateTask.CallFunction = field.NewString(tableName, "call_function")

	_templateTask.fillFieldMap()

	return _templateTask
}

type templateTask struct {
	templateTaskDo

	ALL          field.Asterisk
	TetaID       field.Int64
	TetaName     field.String
	TetaRoleID   field.Int64
	Description  field.String
	SequenceNo   field.Int16
	IsRequired   field.Bool
	CreatedAt    field.Time
	UpdatedAt    field.Time
	CallFunction field.String

	fieldMap map[string]field.Expr
}

func (t templateTask) Table(newTableName string) *templateTask {
	t.templateTaskDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t templateTask) As(alias string) *templateTask {
	t.templateTaskDo.DO = *(t.templateTaskDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *templateTask) updateTableName(table string) *templateTask {
	t.ALL = field.NewAsterisk(table)
	t.TetaID = field.NewInt64(table, "teta_id")
	t.TetaName = field.NewString(table, "teta_name")
	t.TetaRoleID = field.NewInt64(table, "teta_role_id")
	t.Description = field.NewString(table, "description")
	t.SequenceNo = field.NewInt16(table, "sequence_no")
	t.IsRequired = field.NewBool(table, "is_required")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.CallFunction = field.NewString(table, "call_function")

	t.fillFieldMap()

	return t
}

func (t *templateTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *templateTask) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["teta_id"] = t.TetaID
	t.fieldMap["teta_name"] = t.TetaName
	t.fieldMap["teta_role_id"] = t.TetaRoleID
	t.fieldMap["description"] = t.Description
	t.fieldMap["sequence_no"] = t.SequenceNo
	t.fieldMap["is_required"] = t.IsRequired
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["call_function"] = t.CallFunction
}

func (t templateTask) clone(db *gorm.DB) templateTask {
	t.templateTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t templateTask) replaceDB(db *gorm.DB) templateTask {
	t.templateTaskDo.ReplaceDB(db)
	return t
}

type templateTaskDo struct{ gen.DO }

type ITemplateTaskDo interface {
	gen.SubQuery
	Debug() ITemplateTaskDo
	WithContext(ctx context.Context) ITemplateTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITemplateTaskDo
	WriteDB() ITemplateTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITemplateTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITemplateTaskDo
	Not(conds ...gen.Condition) ITemplateTaskDo
	Or(conds ...gen.Condition) ITemplateTaskDo
	Select(conds ...field.Expr) ITemplateTaskDo
	Where(conds ...gen.Condition) ITemplateTaskDo
	Order(conds ...field.Expr) ITemplateTaskDo
	Distinct(cols ...field.Expr) ITemplateTaskDo
	Omit(cols ...field.Expr) ITemplateTaskDo
	Join(table schema.Tabler, on ...field.Expr) ITemplateTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskDo
	Group(cols ...field.Expr) ITemplateTaskDo
	Having(conds ...gen.Condition) ITemplateTaskDo
	Limit(limit int) ITemplateTaskDo
	Offset(offset int) ITemplateTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITemplateTaskDo
	Unscoped() ITemplateTaskDo
	Create(values ...*model.TemplateTask) error
	CreateInBatches(values []*model.TemplateTask, batchSize int) error
	Save(values ...*model.TemplateTask) error
	First() (*model.TemplateTask, error)
	Take() (*model.TemplateTask, error)
	Last() (*model.TemplateTask, error)
	Find() ([]*model.TemplateTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TemplateTask, err error)
	FindInBatches(result *[]*model.TemplateTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TemplateTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITemplateTaskDo
	Assign(attrs ...field.AssignExpr) ITemplateTaskDo
	Joins(fields ...field.RelationField) ITemplateTaskDo
	Preload(fields ...field.RelationField) ITemplateTaskDo
	FirstOrInit() (*model.TemplateTask, error)
	FirstOrCreate() (*model.TemplateTask, error)
	FindByPage(offset int, limit int) (result []*model.TemplateTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITemplateTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t templateTaskDo) Debug() ITemplateTaskDo {
	return t.withDO(t.DO.Debug())
}

func (t templateTaskDo) WithContext(ctx context.Context) ITemplateTaskDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t templateTaskDo) ReadDB() ITemplateTaskDo {
	return t.Clauses(dbresolver.Read)
}

func (t templateTaskDo) WriteDB() ITemplateTaskDo {
	return t.Clauses(dbresolver.Write)
}

func (t templateTaskDo) Session(config *gorm.Session) ITemplateTaskDo {
	return t.withDO(t.DO.Session(config))
}

func (t templateTaskDo) Clauses(conds ...clause.Expression) ITemplateTaskDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t templateTaskDo) Returning(value interface{}, columns ...string) ITemplateTaskDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t templateTaskDo) Not(conds ...gen.Condition) ITemplateTaskDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t templateTaskDo) Or(conds ...gen.Condition) ITemplateTaskDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t templateTaskDo) Select(conds ...field.Expr) ITemplateTaskDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t templateTaskDo) Where(conds ...gen.Condition) ITemplateTaskDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t templateTaskDo) Order(conds ...field.Expr) ITemplateTaskDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t templateTaskDo) Distinct(cols ...field.Expr) ITemplateTaskDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t templateTaskDo) Omit(cols ...field.Expr) ITemplateTaskDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t templateTaskDo) Join(table schema.Tabler, on ...field.Expr) ITemplateTaskDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t templateTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t templateTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) ITemplateTaskDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t templateTaskDo) Group(cols ...field.Expr) ITemplateTaskDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t templateTaskDo) Having(conds ...gen.Condition) ITemplateTaskDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t templateTaskDo) Limit(limit int) ITemplateTaskDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t templateTaskDo) Offset(offset int) ITemplateTaskDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t templateTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITemplateTaskDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t templateTaskDo) Unscoped() ITemplateTaskDo {
	return t.withDO(t.DO.Unscoped())
}

func (t templateTaskDo) Create(values ...*model.TemplateTask) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t templateTaskDo) CreateInBatches(values []*model.TemplateTask, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t templateTaskDo) Save(values ...*model.TemplateTask) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t templateTaskDo) First() (*model.TemplateTask, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTask), nil
	}
}

func (t templateTaskDo) Take() (*model.TemplateTask, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTask), nil
	}
}

func (t templateTaskDo) Last() (*model.TemplateTask, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTask), nil
	}
}

func (t templateTaskDo) Find() ([]*model.TemplateTask, error) {
	result, err := t.DO.Find()
	return result.([]*model.TemplateTask), err
}

func (t templateTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TemplateTask, err error) {
	buf := make([]*model.TemplateTask, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t templateTaskDo) FindInBatches(result *[]*model.TemplateTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t templateTaskDo) Attrs(attrs ...field.AssignExpr) ITemplateTaskDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t templateTaskDo) Assign(attrs ...field.AssignExpr) ITemplateTaskDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t templateTaskDo) Joins(fields ...field.RelationField) ITemplateTaskDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t templateTaskDo) Preload(fields ...field.RelationField) ITemplateTaskDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t templateTaskDo) FirstOrInit() (*model.TemplateTask, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTask), nil
	}
}

func (t templateTaskDo) FirstOrCreate() (*model.TemplateTask, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateTask), nil
	}
}

func (t templateTaskDo) FindByPage(offset int, limit int) (result []*model.TemplateTask, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t templateTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t templateTaskDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t templateTaskDo) Delete(models ...*model.TemplateTask) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *templateTaskDo) withDO(do gen.Dao) *templateTaskDo {
	t.DO = *do.(*gen.DO)
	return t
}
