// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	CustomerID   int64      `gorm:"column:customer_id;type:bigint;primaryKey;autoIncrement:true" json:"customer_id"`
	Nik          string     `gorm:"column:nik;type:character varying(16);not null" json:"nik"`
	NamaLengkap  string     `gorm:"column:nama_lengkap;type:character varying(100);not null" json:"nama_lengkap"`
	TanggalLahir *time.Time `gorm:"column:tanggal_lahir;type:date" json:"tanggal_lahir"`
	NoHp         string     `gorm:"column:no_hp;type:character varying(15);not null" json:"no_hp"`
	Email        *string    `gorm:"column:email;type:character varying(100)" json:"email"`
	Pekerjaan    *string    `gorm:"column:pekerjaan;type:character varying(80)" json:"pekerjaan"`
	Perusahaan   *string    `gorm:"column:perusahaan;type:character varying(120)" json:"perusahaan"`
	Salary       *float64   `gorm:"column:salary;type:numeric(15,2)" json:"salary"`
	LocationID   *int64     `gorm:"column:location_id;type:bigint;index:idx_customers_location,priority:1" json:"location_id"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
