// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKabupaten = "kabupaten"

// Kabupaten mapped from table <kabupaten>
type Kabupaten struct {
	KabID   int64  `gorm:"column:kab_id;type:bigint;primaryKey;autoIncrement:true" json:"kab_id"`
	KabName string `gorm:"column:kab_name;type:character varying(85);not null" json:"kab_name"`
	ProvID  int64  `gorm:"column:prov_id;type:bigint;not null;index:idx_kabupaten_prov,priority:1" json:"prov_id"`
}

// TableName Kabupaten's table name
func (*Kabupaten) TableName() string {
	return TableNameKabupaten
}
