// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKecamatan = "kecamatan"

// Kecamatan mapped from table <kecamatan>
type Kecamatan struct {
	KecID   int64  `gorm:"column:kec_id;type:bigint;primaryKey;autoIncrement:true" json:"kec_id"`
	KecName string `gorm:"column:kec_name;type:character varying(85);not null" json:"kec_name"`
	KabID   int64  `gorm:"column:kab_id;type:bigint;not null;index:idx_kecamatan_kab,priority:1" json:"kab_id"`
}

// TableName Kecamatan's table name
func (*Kecamatan) TableName() string {
	return TableNameKecamatan
}
