// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKelurahan = "kelurahan"

// Kelurahan mapped from table <kelurahan>
type Kelurahan struct {
	KelID   int64  `gorm:"column:kel_id;type:bigint;primaryKey;autoIncrement:true" json:"kel_id"`
	KelName string `gorm:"column:kel_name;type:character varying(85);not null" json:"kel_name"`
	KecID   int64  `gorm:"column:kec_id;type:bigint;not null;index:idx_kelurahan_kec,priority:1" json:"kec_id"`
}

// TableName Kelurahan's table name
func (*Kelurahan) TableName() string {
	return TableNameKelurahan
}
