// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLeasingTask = "leasing_tasks"

// LeasingTask mapped from table <leasing_tasks>
type LeasingTask struct {
	TaskID          int64      `gorm:"column:task_id;type:bigint;primaryKey;autoIncrement:true" json:"task_id"`
	TaskName        string     `gorm:"column:task_name;type:character varying(85);not null" json:"task_name"`
	Startdate       *time.Time `gorm:"column:startdate;type:date" json:"startdate"`
	Enddate         *time.Time `gorm:"column:enddate;type:date" json:"enddate"`
	ActualStartdate *time.Time `gorm:"column:actual_startdate;type:date" json:"actual_startdate"`
	ActualEnddate   *time.Time `gorm:"column:actual_enddate;type:date" json:"actual_enddate"`
	Status          *string    `gorm:"column:status;type:character varying(15);default:inprogress" json:"status"`
	ContractID      int64      `gorm:"column:contract_id;type:bigint;not null;index:idx_task_kontrak,priority:1" json:"contract_id"`
	RoleID          int64      `gorm:"column:role_id;type:bigint;not null;index:idx_task_role,priority:1" json:"role_id"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	SequenceNo      *int16     `gorm:"column:sequence_no;type:smallint" json:"sequence_no"`
	CallFunction    *string    `gorm:"column:call_function;type:text" json:"call_function"`
}

// TableName LeasingTask's table name
func (*LeasingTask) TableName() string {
	return TableNameLeasingTask
}
