// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLeasingContract = "leasing_contract"

// LeasingContract mapped from table <leasing_contract>
type LeasingContract struct {
	ContractID        int64      `gorm:"column:contract_id;type:bigint;primaryKey;autoIncrement:true" json:"contract_id"`
	ContractNumber    *string    `gorm:"column:contract_number;type:character varying(30)" json:"contract_number"`
	RequestDate       time.Time  `gorm:"column:request_date;type:date;not null;default:CURRENT_DATE" json:"request_date"`
	TanggalAkad       *time.Time `gorm:"column:tanggal_akad;type:date" json:"tanggal_akad"`
	TanggalMulaiCicil *time.Time `gorm:"column:tanggal_mulai_cicil;type:date" json:"tanggal_mulai_cicil"`
	TenorBulan        int16      `gorm:"column:tenor_bulan;type:smallint;not null" json:"tenor_bulan"`
	NilaiKendaraan    float64    `gorm:"column:nilai_kendaraan;type:numeric(15,2);not null" json:"nilai_kendaraan"`
	DpDibayar         float64    `gorm:"column:dp_dibayar;type:numeric(15,2);not null" json:"dp_dibayar"`
	PokokPinjaman     float64    `gorm:"column:pokok_pinjaman;type:numeric(15,2);not null" json:"pokok_pinjaman"`
	TotalPinjaman     float64    `gorm:"column:total_pinjaman;type:numeric(15,2);not null" json:"total_pinjaman"`
	CicilanPerBulan   float64    `gorm:"column:cicilan_per_bulan;type:numeric(15,2);not null" json:"cicilan_per_bulan"`
	Status            string     `gorm:"column:status;type:character varying(20);not null;index:idx_kontrak_status,priority:1;default:draft" json:"status"`
	CreatedAt         *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CustomerID        int64      `gorm:"column:customer_id;type:bigint;not null;index:idx_kontrak_customer,priority:1" json:"customer_id"`
	MotorID           int64      `gorm:"column:motor_id;type:bigint;not null;index:idx_kontrak_motor,priority:1" json:"motor_id"`
	ProductID         int64      `gorm:"column:product_id;type:bigint;not null;index:idx_kontrak_product,priority:1" json:"product_id"`
}

// TableName LeasingContract's table name
func (*LeasingContract) TableName() string {
	return TableNameLeasingContract
}
