// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLeasingProduct = "leasing_product"

// LeasingProduct mapped from table <leasing_product>
type LeasingProduct struct {
	ProductID   int64      `gorm:"column:product_id;type:bigint;primaryKey;autoIncrement:true" json:"product_id"`
	KodeProduk  string     `gorm:"column:kode_produk;type:character varying(20);not null" json:"kode_produk"`
	NamaProduk  string     `gorm:"column:nama_produk;type:character varying(100);not null" json:"nama_produk"`
	TenorBulan  int16      `gorm:"column:tenor_bulan;type:smallint;not null" json:"tenor_bulan"`
	DpPersenMin float64    `gorm:"column:dp_persen_min;type:numeric(5,2);not null" json:"dp_persen_min"`
	DpPersenMax float64    `gorm:"column:dp_persen_max;type:numeric(5,2);not null" json:"dp_persen_max"`
	BungaFlat   float64    `gorm:"column:bunga_flat;type:numeric(5,2);not null" json:"bunga_flat"`
	AdminFee    *float64   `gorm:"column:admin_fee;type:numeric(12,2)" json:"admin_fee"`
	Asuransi    *bool      `gorm:"column:asuransi;type:boolean;default:true" json:"asuransi"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName LeasingProduct's table name
func (*LeasingProduct) TableName() string {
	return TableNameLeasingProduct
}
