// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLeasingTasksAttribute = "leasing_tasks_attributes"

// LeasingTasksAttribute mapped from table <leasing_tasks_attributes>
type LeasingTasksAttribute struct {
	TasaID     int64      `gorm:"column:tasa_id;type:bigint;primaryKey;autoIncrement:true" json:"tasa_id"`
	TasaName   string     `gorm:"column:tasa_name;type:character varying(55);not null" json:"tasa_name"`
	TasaValue  *string    `gorm:"column:tasa_value;type:character varying(255)" json:"tasa_value"`
	TasaStatus *string    `gorm:"column:tasa_status;type:character varying(15);default:inprogress" json:"tasa_status"`
	TasaTaskID int64      `gorm:"column:tasa_task_id;type:bigint;not null" json:"tasa_task_id"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName LeasingTasksAttribute's table name
func (*LeasingTasksAttribute) TableName() string {
	return TableNameLeasingTasksAttribute
}
