// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	LocationID    int64    `gorm:"column:location_id;type:bigint;primaryKey;autoIncrement:true" json:"location_id"`
	StreetAddress *string  `gorm:"column:street_address;type:text" json:"street_address"`
	PostalCode    *string  `gorm:"column:postal_code;type:character varying(10)" json:"postal_code"`
	Longitude     *float64 `gorm:"column:longitude;type:numeric(9,6)" json:"longitude"`
	Latitude      *float64 `gorm:"column:latitude;type:numeric(9,6)" json:"latitude"`
	KelID         *int64   `gorm:"column:kel_id;type:bigint;index:idx_locations_kel,priority:1" json:"kel_id"`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
