// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMotor = "motors"

// Motor mapped from table <motors>
type Motor struct {
	MotorID     int64      `gorm:"column:motor_id;type:bigint;primaryKey;autoIncrement:true" json:"motor_id"`
	Merk        string     `gorm:"column:merk;type:character varying(50);not null;index:idx_motors_merk_type,priority:1;default:Honda" json:"merk"`
	MotorType   *string    `gorm:"column:motor_type;type:character varying(15);index:idx_motors_merk_type,priority:2" json:"motor_type"`
	Tahun       int16      `gorm:"column:tahun;type:smallint;not null" json:"tahun"`
	Warna       *string    `gorm:"column:warna;type:character varying(30)" json:"warna"`
	NomorRangka string     `gorm:"column:nomor_rangka;type:character varying(30);not null" json:"nomor_rangka"`
	NomorMesin  string     `gorm:"column:nomor_mesin;type:character varying(30);not null" json:"nomor_mesin"`
	CcMesin     *string    `gorm:"column:cc_mesin;type:character varying(30)" json:"cc_mesin"`
	NomorPolisi *string    `gorm:"column:nomor_polisi;type:character varying(12)" json:"nomor_polisi"`
	StatusUnit  *string    `gorm:"column:status_unit;type:character varying(20);index:idx_motors_status,priority:1;default:ready" json:"status_unit"`
	HargaOtr    float64    `gorm:"column:harga_otr;type:numeric(15,2);not null" json:"harga_otr"`
	MotorMotyID int64      `gorm:"column:motor_moty_id;type:bigint;not null;index:idx_motors_moty_id,priority:1" json:"motor_moty_id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Motor's table name
func (*Motor) TableName() string {
	return TableNameMotor
}
