// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMotorAsset = "motor_assets"

// MotorAsset mapped from table <motor_assets>
type MotorAsset struct {
	MoasID      int64      `gorm:"column:moas_id;type:bigint;primaryKey;autoIncrement:true" json:"moas_id"`
	FileName    string     `gorm:"column:file_name;type:character varying(125);not null" json:"file_name"`
	FileSize    *float64   `gorm:"column:file_size;type:double precision" json:"file_size"`
	FileType    *string    `gorm:"column:file_type;type:character varying(15)" json:"file_type"`
	FileURL     string     `gorm:"column:file_url;type:character varying(255);not null" json:"file_url"`
	MoasMotorID int64      `gorm:"column:moas_motor_id;type:bigint;not null;index:idx_motor_assets_motor,priority:1" json:"moas_motor_id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName MotorAsset's table name
func (*MotorAsset) TableName() string {
	return TableNameMotorAsset
}
