// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePaymentSchedule = "payment_schedule"

// PaymentSchedule mapped from table <payment_schedule>
type PaymentSchedule struct {
	ScheduleID       int64      `gorm:"column:schedule_id;type:bigint;primaryKey;autoIncrement:true" json:"schedule_id"`
	AngsuranKe       int16      `gorm:"column:angsuran_ke;type:smallint;not null" json:"angsuran_ke"`
	JatuhTempo       time.Time  `gorm:"column:jatuh_tempo;type:date;not null" json:"jatuh_tempo"`
	Pokok            float64    `gorm:"column:pokok;type:numeric(15,2);not null" json:"pokok"`
	Margin           float64    `gorm:"column:margin;type:numeric(15,2);not null" json:"margin"`
	TotalTagihan     float64    `gorm:"column:total_tagihan;type:numeric(15,2);not null" json:"total_tagihan"`
	StatusPembayaran *string    `gorm:"column:status_pembayaran;type:character varying(20);default:unpaid" json:"status_pembayaran"`
	TanggalBayar     *time.Time `gorm:"column:tanggal_bayar;type:date" json:"tanggal_bayar"`
	CreatedAt        *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	ContractID       int64      `gorm:"column:contract_id;type:bigint;not null;index:idx_jadwal_kontrak,priority:1" json:"contract_id"`
}

// TableName PaymentSchedule's table name
func (*PaymentSchedule) TableName() string {
	return TableNamePaymentSchedule
}
