// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayment = "payments"

// Payment mapped from table <payments>
type Payment struct {
	PaymentID        int64      `gorm:"column:payment_id;type:bigint;primaryKey;autoIncrement:true" json:"payment_id"`
	NomorBukti       string     `gorm:"column:nomor_bukti;type:character varying(40);not null" json:"nomor_bukti"`
	JumlahBayar      float64    `gorm:"column:jumlah_bayar;type:numeric(15,2);not null" json:"jumlah_bayar"`
	TanggalBayar     time.Time  `gorm:"column:tanggal_bayar;type:date;not null" json:"tanggal_bayar"`
	MetodePembayaran string     `gorm:"column:metode_pembayaran;type:character varying(30);not null" json:"metode_pembayaran"`
	Provider         *string    `gorm:"column:provider;type:character varying(50)" json:"provider"`
	CreatedAt        *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	ContractID       int64      `gorm:"column:contract_id;type:bigint;not null;index:idx_bayar_kontrak,priority:1" json:"contract_id"`
	ScheduleID       *int64     `gorm:"column:schedule_id;type:bigint" json:"schedule_id"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
