// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRolePermission = "role_permission"

// RolePermission mapped from table <role_permission>
type RolePermission struct {
	RolePermissionID int64 `gorm:"column:role_permission_id;type:bigint;primaryKey;autoIncrement:true" json:"role_permission_id"`
	RoleID           int64 `gorm:"column:role_id;type:bigint;not null;index:idx_role_permission_role,priority:1" json:"role_id"`
	PermissionID     int64 `gorm:"column:permission_id;type:bigint;not null" json:"permission_id"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
