// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemplateTask = "template_tasks"

// TemplateTask mapped from table <template_tasks>
type TemplateTask struct {
	TetaID       int64      `gorm:"column:teta_id;type:bigint;primaryKey;autoIncrement:true" json:"teta_id"`
	TetaName     string     `gorm:"column:teta_name;type:character varying(85);not null" json:"teta_name"`
	TetaRoleID   int64      `gorm:"column:teta_role_id;type:bigint;not null;index:idx_template_tasks_role,priority:1" json:"teta_role_id"`
	Description  *string    `gorm:"column:description;type:text" json:"description"`
	SequenceNo   *int16     `gorm:"column:sequence_no;type:smallint;index:idx_template_tasks_seq,priority:1" json:"sequence_no"`
	IsRequired   *bool      `gorm:"column:is_required;type:boolean;default:true" json:"is_required"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CallFunction *string    `gorm:"column:call_function;type:text" json:"call_function"`
}

// TableName TemplateTask's table name
func (*TemplateTask) TableName() string {
	return TableNameTemplateTask
}
