// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemplateTaskAttribute = "template_task_attributes"

// TemplateTaskAttribute mapped from table <template_task_attributes>
type TemplateTaskAttribute struct {
	TetatID       int64      `gorm:"column:tetat_id;type:bigint;primaryKey;autoIncrement:true" json:"tetat_id"`
	TetatName     string     `gorm:"column:tetat_name;type:character varying(85);not null" json:"tetat_name"`
	TetatTetaID   int64      `gorm:"column:tetat_teta_id;type:bigint;not null;index:idx_tetat_teta,priority:1" json:"tetat_teta_id"`
	Description   *string    `gorm:"column:description;type:text" json:"description"`
	IsRequired    *bool      `gorm:"column:is_required;type:boolean;default:true" json:"is_required"`
	AttributeType *string    `gorm:"column:attribute_type;type:character varying(50)" json:"attribute_type"`
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName TemplateTaskAttribute's table name
func (*TemplateTaskAttribute) TableName() string {
	return TableNameTemplateTaskAttribute
}
