// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID         int64      `gorm:"column:user_id;type:bigint;primaryKey;autoIncrement:true" json:"user_id"`
	Username       *string    `gorm:"column:username;type:character varying(50)" json:"username"`
	PhoneNumber    string     `gorm:"column:phone_number;type:character varying(15);not null;index:idx_users_phone_login,priority:1" json:"phone_number"`
	Email          *string    `gorm:"column:email;type:character varying(100);index:idx_users_email,priority:1" json:"email"`
	FullName       string     `gorm:"column:full_name;type:character varying(100);not null" json:"full_name"`
	Password       *string    `gorm:"column:password;type:character varying(255)" json:"password"`
	PinKey         *string    `gorm:"column:pin_key;type:character varying(255)" json:"pin_key"`
	IsActive       *bool      `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
	LastLogin      *time.Time `gorm:"column:last_login;type:timestamp with time zone" json:"last_login"`
	FailedAttempts *int16     `gorm:"column:failed_attempts;type:smallint" json:"failed_attempts"`
	LockedUntil    *time.Time `gorm:"column:locked_until;type:timestamp with time zone" json:"locked_until"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
